const cropData = [
    {
        id: 1,
        name: "Wheat",
        state: "Punjab",
        price: 2150,
        unit: "quintal",
        trend: "up",
        change: "+2.5%",
      },
      {
        id: 2,
        name: "Wheat",
        state: "Haryana",
        price: 2100,
        unit: "quintal",
        trend: "up",
        change: "+1.8%",
      },
      {
        id: 3,
        name: "Wheat",
        state: "Uttar Pradesh",
        price: 2080,
        unit: "quintal",
        trend: "down",
        change: "-1.2%",
      },
      {
        id: 4,
        name: "Wheat",
        state: "Rajasthan",
        price: 2075,
        unit: "quintal",
        trend: "down",
        change: "-0.9%",
      },
      {
        id: 5,
        name: "Wheat",
        state: "Madhya Pradesh",
        price: 2120,
        unit: "quintal",
        trend: "up",
        change: "+1.1%",
      },
      {
        id: 6,
        name: "Wheat",
        state: "Gujarat",
        price: 2090,
        unit: "quintal",
        trend: "down",
        change: "-0.5%",
      },
      {
        id: 7,
        name: "Wheat",
        state: "Bihar",
        price: 2060,
        unit: "quintal",
        trend: "down",
        change: "-1.6%",
      },
      {
        id: 8,
        name: "Wheat",
        state: "Maharashtra",
        price: 2130,
        unit: "quintal",
        trend: "up",
        change: "+2.0%",
      },
      {
        id: 9,
        name: "Wheat",
        state: "Chhattisgarh",
        price: 2110,
        unit: "quintal",
        trend: "up",
        change: "+0.7%",
      },
      {
        id: 10,
        name: "Wheat",
        state: "West Bengal",
        price: 2040,
        unit: "quintal",
        trend: "down",
        change: "-2.1%",
      },
  {
    id: 4,
    name: "Rice",
    state: "Punjab",
    price: 1950,
    unit: "quintal",
    trend: "up",
    change: "+3.2%",
  },
  {
    id: 5,
    name: "Rice",
    state: "West Bengal",
    price: 1850,
    unit: "quintal",
    trend: "stable",
    change: "0%",
  },
  {
    id: 6,
    name: "Rice",
    state: "Andhra Pradesh",
    price: 1800,
    unit: "quintal",
    trend: "down",
    change: "-0.8%",
  },
  {
    id: 7,
    name: "Cotton",
    state: "Gujarat",
    price: 6200,
    unit: "quintal",
    trend: "up",
    change: "+4.1%",
  },
  {
    id: 8,
    name: "Cotton",
    state: "Maharashtra",
    price: 6150,
    unit: "quintal",
    trend: "up",
    change: "+3.8%",
  },
  {
    id: 9,
    name: "Cotton",
    state: "Rajasthan",
    price: 6000,
    unit: "quintal",
    trend: "stable",
    change: "0%",
  },
  {
    id: 10,
    name: "Sugarcane",
    state: "Uttar Pradesh",
    price: 340,
    unit: "quintal",
    trend: "up",
    change: "+2.1%",
  },
  {
    id: 11,
    name: "Sugarcane",
    state: "Maharashtra",
    price: 330,
    unit: "quintal",
    trend: "stable",
    change: "0%",
  },
  {
    id: 12,
    name: "Sugarcane",
    state: "Karnataka",
    price: 320,
    unit: "quintal",
    trend: "down",
    change: "-1.5%",
  },
  {
    id: 13,
    name: "Soybean",
    state: "Madhya Pradesh",
    price: 4500,
    unit: "quintal",
    trend: "up",
    change: "+5.2%",
  },
  {
    id: 14,
    name: "Soybean",
    state: "Maharashtra",
    price: 4450,
    unit: "quintal",
    trend: "up",
    change: "+4.8%",
  },
  {
    id: 15,
    name: "Soybean",
    state: "Rajasthan",
    price: 4400,
    unit: "quintal",
    trend: "up",
    change: "+3.9%",
  },
  {
    id: 16,
    name: "Maize",
    state: "Karnataka",
    price: 1850,
    unit: "quintal",
    trend: "up",
    change: "+2.8%",
  },
  {
    id: 17,
    name: "Maize",
    state: "Andhra Pradesh",
    price: 1820,
    unit: "quintal",
    trend: "stable",
    change: "0%",
  },
  {
    id: 18,
    name: "Maize",
    state: "Maharashtra",
    price: 1800,
    unit: "quintal",
    trend: "down",
    change: "-0.9%",
  },
  {
    id: 19,
    name: "Turmeric",
    state: "Tamil Nadu",
    price: 8500,
    unit: "quintal",
    trend: "up",
    change: "+6.2%",
  },
  {
    id: 20,
    name: "Turmeric",
    state: "Andhra Pradesh",
    price: 8200,
    unit: "quintal",
    trend: "up",
    change: "+4.5%",
  },
  {
    id: 21,
    name: "Onion",
    state: "Maharashtra",
    price: 1200,
    unit: "quintal",
    trend: "down",
    change: "-8.3%",
  },
  {
    id: 22,
    name: "Onion",
    state: "Karnataka",
    price: 1150,
    unit: "quintal",
    trend: "down",
    change: "-7.1%",
  },
  {
    id: 23,
    name: "Potato",
    state: "Uttar Pradesh",
    price: 1500,
    unit: "quintal",
    trend: "up",
    change: "+12.5%",
  },
  {
    id: 24,
    name: "Potato",
    state: "West Bengal",
    price: 1400,
    unit: "quintal",
    trend: "up",
    change: "+10.2%",
  },
  {
    id: 25,
    name: "Tomato",
    state: "Karnataka",
    price: 2800,
    unit: "quintal",
    trend: "down",
    change: "-15.2%",
  },
  {
    id: 26,
    name: "Tomato",
    state: "Maharashtra",
    price: 2600,
    unit: "quintal",
    trend: "down",
    change: "-18.5%",
  },
];
export default cropData;