import { createContext, useContext, useState, ReactNode } from "react";

export type LangCode = "en" | "hi" | "bn" | "te" | "ta";

export interface LanguageOption {
  code: LangCode;
  name: string;
  nativeName: string;
  speechCode: string;
}

export const LANGUAGES: LanguageOption[] = [
  { code: "en", name: "English", nativeName: "English", speechCode: "en-IN" },
  { code: "hi", name: "Hindi", nativeName: "हिंदी", speechCode: "hi-IN" },
  { code: "bn", name: "Bengali", nativeName: "বাংলা", speechCode: "bn-IN" },
  { code: "te", name: "Telugu", nativeName: "తెలుగు", speechCode: "te-IN" },
  { code: "ta", name: "Tamil", nativeName: "தமிழ்", speechCode: "ta-IN" },
];

interface LanguageContextType {
  language: LangCode;
  setLanguage: (lang: LangCode) => void;
  t: (key: string) => string;
  currentLangOption: LanguageOption;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<LangCode>(() => {
    const saved = localStorage.getItem("pk-language");
    return (saved as LangCode) || "en";
  });

  const handleSetLanguage = (lang: LangCode) => {
    setLanguage(lang);
    localStorage.setItem("pk-language", lang);
  };

  const t = (key: string): string => {
    return translations[language]?.[key] || translations.en[key] || key;
  };

  const currentLangOption = LANGUAGES.find((l) => l.code === language) || LANGUAGES[0];

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t, currentLangOption }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error("useLanguage must be used within LanguageProvider");
  return ctx;
}

/* eslint-disable @typescript-eslint/no-use-before-define */

const en_t: Record<string, string> = {
  // ── Sarthi / Assistant ──
  sarthiTitle: "Sarthi AI Assistant",
  askPlaceholder: "Ask Sarthi something...",
  welcomeTitle: "Welcome to Sarthi!",
  welcomeSubtitle: "How can I help you today?",
  selectLanguage: "Select Language",
  currentLabel: "Current",
  clickMicToStart: "Click the mic to start",
  listening: "Listening...",
  sendToChat: "Send to chat",
  errorResponse: "Sorry, I couldn't get a response. Please try again.",
  connectionError: "Unable to connect to server. Please check your connection.",
  typing: "Sarthi is typing...",
  errorRetrievingResponse: "Error retrieving response.",
  failedConnectServer: "Failed to connect to server.",
  voiceControlTitle: "Voice Control",
  startVoiceCommand: "Start Voice Command",
  pageNotFound: "404",
  oopsPageNotFound: "Oops! Page not found",
  returnToHome: "Return to Home",

  // ── Navbar ──
  navHome: "Home",
  navPriceEstimation: "Price Estimation",
  navCropHealth: "Crop Health",
  navSchemes: "Schemes",
  navMarket: "Market",
  navLand: "Land",
  navPrices: "Prices",
  navWeather: "Weather",
  navToken: "Token",
  projectKisan: "Project",
  projectKisanHighlight: "Kisan",
  logIn: "Log in",
  dashboard: "Dashboard",

  // ── Hero Section ──
  heroBadge: "AI-Powered Agriculture Platform",
  heroTitle: "Smarter Farming,",
  heroTitleHighlight: "Better Returns",
  heroSubtitle: "Leverage AI to estimate crop prices, monitor plant health, discover government schemes, and connect directly with buyers — all in one platform built for Indian farmers.",
  getStartedFree: "Get Started Free",
  checkCropHealth: "Check Crop Health",
  trustedBy: "Trusted by",
  trustedCount: "1,000+",
  farmersAcrossIndia: "farmers across India",
  activeCrops: "Active Crops",
  healthScore: "Health Score",
  priceAlerts: "Price Alerts",
  estRevenue: "Est. Revenue",
  priceTrends: "Price Trends",
  last7Days: "Last 7 days",

  // ── Features Section (Index page) ──
  features: "FEATURES",
  featuresTitle: "Everything farmers need,",
  featuresTitleHighlight: "in one place",
  featuresSubtitle: "Comprehensive AI-powered tools to revolutionize farming operations and maximize profitability.",
  priceEstimation: "Price Estimation",
  priceEstimationDesc: "AI-powered crop price forecasts based on land, resources, and real-time market data.",
  aiPowered: "AI-Powered",
  cropHealth: "Crop Health",
  cropHealthDesc: "Upload crop images for instant health assessments, disease detection, and treatment advice.",
  computerVision: "Computer Vision",
  govSchemes: "Government Schemes",
  govSchemesDesc: "Stay updated with the latest agricultural subsidies, loans, and scheme deadlines.",
  updatedWeekly: "Updated Weekly",
  directMarket: "Direct Market",
  directMarketDesc: "Connect directly with buyers and industries — sell produce without intermediaries.",
  marketplace: "Marketplace",
  landRecords: "Land Records",
  landRecordsDesc: "Manage land listings, explore agricultural land, and track ownership records.",
  landManagement: "Land Management",
  weatherPrices: "Weather & Prices",
  weatherPricesDesc: "Real-time weather forecasts and daily mandi price updates for your region.",
  liveData: "Live Data",
  learnMore: "Learn more",

  // ── Welcome toast ──
  welcomeToast: "Welcome to Project Kisan",
  welcomeToastDesc: "Explore AI tools designed specifically for Indian farmers.",

  // ── Why Choose Section ──
  whyBadge: "WHY PROJECT KISAN",
  whyTitle: "Built for the future of Indian agriculture",
  whySubtitle: "Our platform combines cutting-edge AI with deep agricultural domain knowledge to help farmers make data-driven decisions.",
  whyItem1: "Advanced AI algorithms for accurate price predictions",
  whyItem2: "Real-time crop health monitoring with computer vision",
  whyItem3: "Comprehensive government schemes database",
  whyItem4: "Direct marketplace — no middlemen",
  whyItem5: "Designed for farmers of all tech levels",
  getStartedNow: "Get Started Now",
  cropAnalysisDashboard: "Crop Analysis Dashboard",
  realTimeMonitoring: "Real-time monitoring",
  health: "Health",
  pricePerKg: "Price/kg",
  yield: "Yield",

  // ── CTA Section ──
  ctaTitle: "Ready to transform your farming?",
  ctaSubtitle: "Join thousands of farmers already using Project Kisan to increase productivity and profitability.",
  startFreeToday: "Start Free Today",
  viewDashboard: "View Dashboard",

  // ── Stats Section ──
  farmersOnPlatform: "Farmers on Platform",
  cropsMonitored: "Crops Monitored",
  pricePredictions: "Price Predictions",
  districtsCovered: "Districts Covered",

  // ── Footer ──
  footerPlatform: "Platform",
  footerResources: "Resources",
  footerCompany: "Company",
  footerWeather: "Weather",
  footerMarketPrices: "Market Prices",
  footerWorkspace: "Workspace",
  footerAbout: "About",
  footerPrivacy: "Privacy Policy",
  footerTerms: "Terms of Service",
  footerContact: "Contact",
  footerDescription: "AI-powered tools to help Indian farmers make smarter decisions and increase profitability.",
  footerCopyright: "Project Kisan. All rights reserved.",
  footerTagline: "Built with AI for Indian farmers",

  // ── Government Schemes ──
  schemesTitle: "Government Schemes & Loans",
  schemesSubtitle: "Discover the latest agricultural support programs, subsidies, and loan offers",
  searchSchemes: "Search for schemes, loans, or agencies...",
  all: "All",
  subsidies: "Subsidies",
  loans: "Loans",
  grants: "Grants",
  noSchemesFound: "No Schemes Found",
  noSchemesDesc: "We couldn't find any schemes matching your search criteria. Try adjusting your search or check back later.",
  noSubsidiesFound: "No Subsidies Found",
  noLoansFound: "No Loans Found",
  noGrantsFound: "No Grants Found",
  needHelpTitle: "Need Help With Applications?",
  needHelpDesc: "Our experts can guide you through the application process for any of the schemes listed above.",
  getAppAssistance: "Get Application Assistance",
  by: "By",
  deadline: "Deadline",
  details: "Details",

  // ── Crop Health Page ──
  cropHealthTitle: "Crop Health Analysis",
  cropHealthSubtitle: "Upload images of your crops to get AI-powered health assessments and recommendations",
  howItWorks: "How It Works",
  howItWorksDesc: "Our AI system can detect diseases, nutrient deficiencies, and other health issues",
  visualAnalysis: "Visual Analysis",
  visualAnalysisDesc: "Our AI algorithm analyzes visual patterns, colors, and textures in your crop images.",
  diseaseDetection: "Disease Detection",
  diseaseDetectionDesc: "Identifies common crop diseases like leaf rust, powdery mildew, and blight with high accuracy.",
  healthAssessment: "Health Assessment",
  healthAssessmentDesc: "Provides an overall health score and identifies specific areas of concern.",
  personalizedRec: "Personalized Recommendations",
  personalizedRecDesc: "Offers tailored suggestions for treatment, fertilization, and care based on the analysis.",
  forBestResults: "For Best Results",
  tipClearPhotos: "Take clear, well-lit photos",
  tipAvoidShadows: "Avoid shadows and blur",
  tipIncludeParts: "Include healthy & unhealthy parts",
  tipAngles: "Provide multiple angles",
  analysisResults: "Analysis Results",
  confidence: "Confidence",
  healthScoreLabel: "Health Score",
  detectedIssue: "Detected Issue",
  recommendations: "Recommendations",
  excellent: "Excellent",
  good: "Good",
  fair: "Fair",
  poor: "Poor",
  critical: "Critical",
  seasonalCrops: "Seasonal Crops in India",
  seasonalCropsDesc: "Recommended crops for the current season, common diseases, and treatment options",
  commonDiseases: "Common Diseases",
  symptoms: "Symptoms",
  remedies: "Remedies",
  recommendedFertilizers: "Recommended Fertilizers",
  dataUpdated: "Data updated for growing season in India",
  consultExperts: "Always consult with local agricultural experts",
  checkCropHealthBtn: "Check Crop Health",
  uploadedImage: "Uploaded Image",
  analyzing: "Analyzing...",
  analyzeCropHealth: "Analyze Crop Health",
  analyzingImage: "Analyzing image...",
  analyzingImageDesc: "Please wait while we assess your crop's health.",
  analysisComplete: "Analysis Complete",
  analysisCompleteDesc: "We've completed the health assessment of your crop.",

  // ── Price Estimation Page ──
  priceEstTitle: "Crop Price Estimation",
  priceEstSubtitle: "Use our AI-powered tool to estimate the market price of your crops based on various factors",
  marketAnalysis: "Market Analysis",
  marketAnalysisDesc: "Our AI analyzes current and historical market data to establish baseline pricing trends.",
  resourceEvaluation: "Resource Evaluation",
  resourceEvalDesc: "We factor in your land size, water availability, and soil type to refine the estimate.",
  yieldPrediction: "Yield Prediction",
  yieldPredictionDesc: "The system predicts your potential yield quality based on the provided information.",
  priceRangeGen: "Price Range Generation",
  priceRangeDesc: "You receive a comprehensive price range with minimum, average, and maximum estimates.",
  didYouKnow: "Did you know?",
  didYouKnowText: "Farmers who use price estimation tools can increase their profit margins by up to 15% by timing their market entry more strategically.",
  cropYieldEstimation: "Crop Yield Estimation",
  estimate: "Estimate",
  estimationResult: "Estimation Result",
  estimatedYield: "Estimated Yield:",
  waterRequired: "Water Required:",
  diseases: "Diseases:",
  fertilizerRec: "Fertilizer Recommendation:",
  remark: "Remark:",
  estimatedSales: "Estimated Sales:",
  estimatedCost: "Estimated Cost:",
  fetchError: "Failed to fetch estimation. Please try again.",
  serverError: "Error connecting to the server.",

  // ── Direct Market ──
  directMarketTitle: "Direct Market Access",
  directMarketSubtitle: "Connect directly with consumers and industries to sell or lease your produce without intermediaries",
  searchMarket: "Search by product, location, or seller...",
  allListings: "All Listings",
  forSale: "For Sale",
  forLease: "For Lease",
  listYourProduct: "List Your Product",
  listNewProduct: "List a New Product",
  listNewProductDesc: "Enter your product details to list it on the marketplace.",
  productTitle: "Product Title",
  enterProductName: "Enter product name",
  price: "Price",
  priceInRupees: "₹00/unit",
  quantityAvailable: "Quantity Available",
  quantityPlaceholder: "e.g., 500 kg available",
  location: "Location",
  cityState: "City, State",
  sellerName: "Seller Name",
  sellerNamePlaceholder: "Your name or business name",
  category: "Category",
  categoryPlaceholder: "e.g., Vegetables, Grains",
  marketType: "Market Type",
  selectMarketType: "Select market type",
  consumerMarket: "Consumer Market",
  industrySupply: "Industry Supply",
  equipmentRental: "Equipment Rental",
  listingType: "Listing Type",
  imageUrl: "Image URL (Optional)",
  enterImageUrl: "Enter image URL",
  cancel: "Cancel",
  listProduct: "List Product",
  contactRequestSent: "Contact Request Sent",
  contactRequestDesc: "Your request to contact the seller has been sent.",
  missingInfo: "Missing Information",
  fillRequired: "Please fill in all required fields.",
  productListed: "Product Listed Successfully",
  productListedDesc: "Your product has been added to the marketplace.",
  contactSeller: "Contact Seller",
  quantity: "Quantity:",
  seller: "Seller:",
  listingTypeLabel: "Listing Type:",
  noProductsFound: "No products found",
  noProductsHint: "Try adjusting your search or filter",
  beFirstToList: "Be the first to list a product in this category",
  needTransport: "Need Transportation for Your Goods?",
  needTransportDesc: "Connect with local logistics providers to transport your produce.",
  findTransport: "Find Transportation",

  // ── Prices Page ──
  cropPrices: "Crop Prices",
  cropPricesDesc: "Get the latest prices of various crops and commodities across different states. Prices are updated daily and show market trends.",
  searchCrops: "Search for crops (e.g., wheat, rice, cotton...)",
  allStates: "All States",
  showing: "Showing",
  prices: "price(s)",
  for: "for",
  in: "in",
  noCropsFound: "No crops found matching your search criteria.",
  noCropsHint: "Try adjusting your search terms or selecting a different state.",
  marketInfo: "Market Information",
  priceUpdates: "Price Updates:",
  dailyAt: "Daily at 6:00 AM IST",
  currency: "Currency:",
  inrFull: "Indian Rupees (₹)",
  unit: "Unit:",
  perQuintal: "Per Quintal (100 kg)",
  pricesDisclaimer: "* Prices are indicative and may vary based on quality, market conditions, and local factors.",
  per: "per",

  // ── Land Selling ──
  landMarketplace: "Agricultural Land Marketplace",
  mapView: "Map View",
  addListing: "Add Listing",
  viewListings: "View Listings",
  maxPrice: "Max Price",
  minArea: "Min Area (acres)",
  title: "Title",
  area: "Area",
  createdAt: "Created At",
  contact: "Contact",
  listingsLoaded: "Listings loaded",
  listingsLoadedDesc: "land listings from the database.",
  error: "Error",
  failedLoadListings: "Failed to load listings. Please try again later.",
  invalidListing: "Invalid listing",
  fillAllRequired: "Please fill all required fields with valid values.",
  listingAdded: "Listing added",
  listingAddedDesc: "Your land listing has been added successfully and saved to storage.",
  addNewLandListing: "Add New Land Listing",
  addNewLandDesc: "Fill in the details below to list your agricultural land for sale",
  listingTitle: "Listing Title",
  listingTitlePlaceholder: "e.g., Fertile Farmland near Pune",
  description: "Description",
  landDescPlaceholder: "Describe your land, soil quality, nearby water sources, etc.",
  priceRupees: "Price (₹)",
  enterPrice: "Enter price in rupees",
  areaAcres: "Area (acres)",
  landAreaAcres: "Land area in acres",
  contactNumber: "Contact Number",
  enterContact: "Enter your contact number",
  clickMapInstruction: "Click on the map to set the location, or enter coordinates manually:",
  latitude: "Latitude",
  longitude: "Longitude",
  viewOnGoogleMaps: "View on Google Maps",
  reset: "Reset",
  saving: "Saving...",
  validationError: "Validation Error",
  titleRequired: "Title is required",
  descriptionRequired: "Description is required",
  priceGtZero: "Price must be greater than zero",
  areaGtZero: "Area must be greater than zero",
  contactRequired: "Contact number is required",
  success: "Success",
  landListingAdded: "Land listing added successfully!",
  failedAddListing: "Failed to add listing. Please try again.",
  landListingsMap: "Land Listings Map",
  landListingsMapDesc: "Browse available agricultural land for sale. Click on markers to view details.",
  hideFilters: "Hide Filters",
  showFilters: "Show Filters",
  searchByTitle: "Search by Title",
  searchListings: "Search listings...",
  priceRange: "Price Range:",
  areaRange: "Area Range:",
  acres: "acres",
  resetFilters: "Reset Filters",
  of: "of",
  listingsShown: "listings shown",
  loadingMap: "Loading map and listings...",
  noListingsAvailable: "No listings available. Please add some listings first.",
  listingsAvailable: "listing(s) available",
  recentListings: "Recent Listings:",

  // ── Farmer Pages ──
  farmerPortal: "Farmer Portal",
  registerNewAccount: "Register New Account",
  name: "Name",
  landArea: "Land Area",
  phoneNumber: "Phone Number",
  email: "Email",
  password: "Password",
  selectedCrop: "Selected Crop",
  register: "Register",
  registering: "Registering...",
  alreadyRegistered: "Already Registered?",
  enterPhoneNumber: "Enter Phone Number",
  enterPassword: "Enter Password",
  viewDetails: "View Details",
  viewMyDetails: "View My Details",
  errorRegistering: "Error registering farmer",
  loadingFarmerDetails: "Loading farmer details...",
  farmerNotFound: "Farmer not found",
  farmerDetails: "Farmer Details",
  nameLabel: "Name:",
  areaLabel: "Area:",
  landAreaLabel: "Land Area:",
  phoneLabel: "Phone:",
  emailLabel: "Email:",
  dateOfStarting: "Date of Starting:",
  selectedCropLabel: "Selected Crop:",
  notSelected: "Not Selected",
  enterNewCrop: "Enter new crop",
  updating: "Updating...",
  updateCrop: "Update Crop",
  loadingCropInfo: "Loading crop information...",
  cropSchedule: "Crop Schedule:",
  dailyTasks: "Daily Tasks",
  waterSchedule: "Water Schedule",
  growthStages: "Growth Stages",
  fertilizerSchedule: "Fertilizer Schedule",
  day: "Day",
  date: "Date",
  activity: "Activity",
  totalCropDuration: "Total Crop Duration:",
  days: "days",
  sending: "Sending...",
  sendEmail: "Send Email",
  emailSentSuccess: "Email sent successfully!",
  failedSendEmail: "Failed to send email",
  registrationDate: "Registration Date:",
  cropLabel: "Crop:",
  notApplicable: "N/A",

  // ── Weather Page ──
  weatherRainfallTitle: "Weather & Rainfall Analysis",
  weatherRainfallDesc: "Monitor rainfall patterns to plan your agricultural activities effectively.",
  rainfallDataFor: "Rainfall Data for",
  next30Days: "(Next 30 Days)",
  selectState: "Select a state",
  rainfallMm: "Rainfall (mm)",
  rainfallLabel: "Rainfall:",
  conditionLabel: "Condition:",
  weatherImpact: "Weather Impact on Crops",
  weatherImpactDesc: "Understanding rainfall patterns helps in planning irrigation, selecting appropriate crop varieties, and determining planting schedules. Excess or insufficient rainfall can significantly impact crop yields and quality.",
  rainfallRequirements: "Rainfall Requirements:",
  seasonalForecasts: "Seasonal Forecasts",
  seasonalForecastsDesc: "Seasonal forecasts provide valuable insights for agricultural planning. Monitor these trends to make informed decisions for your farming activities.",
  monsoonSeason: "Monsoon Season (June-September)",
  monsoonDesc: "Expected to be normal to above normal across most regions.",
  winterSeason: "Winter Season (October-February)",
  winterDesc: "Predicted to have moderate rainfall in northern and central regions.",

  // ── Token Pages ──
  tokenRegistration: "Token Registration",
  enterName: "Enter Name",
  enterContactNumber: "Enter Contact Number",
  landAreaInAcres: "Land Area (in acres)",
  enterEmail: "Enter Email",
  cropOptional: "Crop (optional)",
  submit: "Submit",
  tokenAdded: "Token added successfully!",
  tokenError: "Error adding token. Please try again.",
  checkStatus: "Check Status",
  status: "Status:",
  allottedDate: "Allotted Date:",
  noRecordFound: "No record found for this phone number.",
  tokenAllotment: "Token Allotment (Admin Only)",
  adminUsername: "Admin Username",
  adminPassword: "Admin Password",
  farmersPhone: "Farmer's Phone Number",
  updateStatus: "Update Status",
  accessDenied: "Access Denied: Invalid Admin Credentials.",
  statusUpdated: "Status and Allotted Date Updated Successfully!",
  tokenUpdateError: "Error updating token. Please try again.",

  // ── Seller Management ──
  sellerManagement: "Seller Management",
  addNewSeller: "Add New Seller",
  itemName: "Item Name",
  contactOptional: "Contact (optional)",
  sellerAdded: "Seller successfully added!",

  // ── Update Crop ──
  updateYourCrop: "Update Your Crop",
  updateCropPaymentDesc: "To update your crop details, please make a secure payment of ₹100.",
  payAmount: "Pay ₹100",
  afterPaymentNote: "After payment, your crop will be updated automatically.",
  paymentSuccessful: "Payment Successful! Payment ID:",
  razorpayFailed: "Razorpay SDK failed to load. Please try again.",

  // ── Workplace ──
  showData: "Show Data",
  apply: "Apply",
  welcome: "Welcome",
  selectOption: "Please select an option from the navbar above.",

  // ── Work Listings / ApplyForm / ShowData ──
  createWorkListing: "Create Work Listing",
  workListingCreated: "Work listing created successfully!",
  failedCreateListing: "Failed to create work listing",
  errorConnecting: "Error connecting to server. Please try again.",
  jobTitle: "Job Title",
  jobTitlePlaceholder: "Enter a clear job title",
  descriptionLabel: "Description",
  jobDescPlaceholder: "Describe the job in detail",
  payment: "Payment",
  paymentPlaceholder: "Payment amount or range",
  locationLabel: "Location",
  locationPlaceholder: "Enter locations separated by commas",
  duration: "Duration",
  durationPlaceholder: "Expected duration of the job",
  categoryLabel: "Category",
  jobCategoryPlaceholder: "Job category",
  requirements: "Requirements",
  requirementsPlaceholder: "Required skills and qualifications",
  contactInfo: "Contact Information",
  contactInfoPlaceholder: "How applicants should contact you",
  submitting: "Submitting...",
  createListing: "Create Listing",
  workListings: "Work Listings",
  failedLoadData: "Failed to load data. Please try again later.",
  loadingListings: "Loading listings...",
  noWorkListings: "No work listings available at the moment",
  requirementsLabel: "Requirements:",
  applyNow: "Apply Now",

  // ── Scheme data (keep in en only, other languages fall back) ──
  clear: "Clear",
};

const hi_t: Record<string, string> = {
  // ── Sarthi ──
  sarthiTitle: "सारथी AI सहायक",
  askPlaceholder: "सारथी से कुछ पूछें...",
  welcomeTitle: "सारथी में आपका स्वागत है!",
  welcomeSubtitle: "आज मैं आपकी कैसे मदद कर सकता हूँ?",
  selectLanguage: "भाषा चुनें",
  currentLabel: "वर्तमान",
  clickMicToStart: "शुरू करने के लिए माइक पर क्लिक करें",
  listening: "सुन रहा हूँ...",
  sendToChat: "चैट पर भेजें",
  errorResponse: "क्षमा करें, उत्तर प्राप्त नहीं हो सका। कृपया पुनः प्रयास करें।",
  connectionError: "सर्वर से कनेक्ट नहीं हो पा रहा। कृपया अपना कनेक्शन जांचें।",
  typing: "सारथी टाइप कर रहा है...",
  errorRetrievingResponse: "प्रतिक्रिया प्राप्त करने में त्रुटि।",
  failedConnectServer: "सर्वर से कनेक्ट होने में विफल।",
  voiceControlTitle: "वॉइस कंट्रोल",
  startVoiceCommand: "वॉइस कमांड शुरू करें",
  pageNotFound: "404",
  oopsPageNotFound: "उफ़! पृष्ठ नहीं मिला",
  returnToHome: "होम पर लौटें",

  // ── Navbar ──
  navHome: "होम",
  navPriceEstimation: "मूल्य अनुमान",
  navCropHealth: "फसल स्वास्थ्य",
  navSchemes: "योजनाएं",
  navMarket: "बाजार",
  navLand: "भूमि",
  navPrices: "कीमतें",
  navWeather: "मौसम",
  navToken: "टोकन",
  projectKisan: "प्रोजेक्ट",
  projectKisanHighlight: "किसान",
  logIn: "लॉग इन",
  dashboard: "डैशबोर्ड",

  // ── Hero ──
  heroBadge: "AI-संचालित कृषि मंच",
  heroTitle: "स्मार्ट खेती,",
  heroTitleHighlight: "बेहतर रिटर्न",
  heroSubtitle: "फसल की कीमतों का अनुमान लगाने, पौधों के स्वास्थ्य की निगरानी करने, सरकारी योजनाओं की खोज करने और सीधे खरीदारों से जुड़ने के लिए AI का उपयोग करें।",
  getStartedFree: "मुफ्त शुरू करें",
  checkCropHealth: "फसल स्वास्थ्य जांचें",
  trustedBy: "विश्वसनीय",
  trustedCount: "1,000+",
  farmersAcrossIndia: "भारत भर के किसान",
  activeCrops: "सक्रिय फसलें",
  healthScore: "स्वास्थ्य स्कोर",
  priceAlerts: "कीमत अलर्ट",
  estRevenue: "अनु. आय",
  priceTrends: "कीमत रुझान",
  last7Days: "पिछले 7 दिन",

  // ── Features ──
  features: "विशेषताएं",
  featuresTitle: "किसानों को जो चाहिए,",
  featuresTitleHighlight: "एक ही जगह",
  featuresSubtitle: "खेती को बदलने और लाभ बढ़ाने के लिए AI-संचालित उपकरण।",
  priceEstimation: "मूल्य अनुमान",
  priceEstimationDesc: "भूमि, संसाधनों और रीयल-टाइम बाजार डेटा पर आधारित AI-संचालित फसल मूल्य पूर्वानुमान।",
  aiPowered: "AI-संचालित",
  cropHealth: "फसल स्वास्थ्य",
  cropHealthDesc: "तत्काल स्वास्थ्य मूल्यांकन, रोग पहचान और उपचार सलाह के लिए फसल चित्र अपलोड करें।",
  computerVision: "कंप्यूटर विज़न",
  govSchemes: "सरकारी योजनाएं",
  govSchemesDesc: "नवीनतम कृषि सब्सिडी, ऋण और योजना समय सीमा से अपडेट रहें।",
  updatedWeekly: "साप्ताहिक अपडेट",
  directMarket: "सीधा बाजार",
  directMarketDesc: "खरीदारों और उद्योगों से सीधे जुड़ें — बिना बिचौलियों के उत्पाद बेचें।",
  marketplace: "बाज़ार",
  landRecords: "भूमि रिकॉर्ड",
  landRecordsDesc: "भूमि लिस्टिंग प्रबंधित करें, कृषि भूमि खोजें और स्वामित्व के रिकॉर्ड ट्रैक करें।",
  landManagement: "भूमि प्रबंधन",
  weatherPrices: "मौसम और कीमतें",
  weatherPricesDesc: "आपके क्षेत्र के लिए रीयल-टाइम मौसम पूर्वानुमान और दैनिक मंडी कीमत अपडेट।",
  liveData: "लाइव डेटा",
  learnMore: "और जानें",

  // ── Welcome toast ──
  welcomeToast: "प्रोजेक्ट किसान में आपका स्वागत है",
  welcomeToastDesc: "भारतीय किसानों के लिए विशेष रूप से डिज़ाइन किए गए AI टूल्स का अन्वेषण करें।",

  // ── Why Choose ──
  whyBadge: "प्रोजेक्ट किसान क्यों",
  whyTitle: "भारतीय कृषि के भविष्य के लिए निर्मित",
  whySubtitle: "हमारा मंच अत्याधुनिक AI को गहन कृषि ज्ञान के साथ जोड़कर किसानों को डेटा-संचालित निर्णय लेने में मदद करता है।",
  whyItem1: "सटीक मूल्य पूर्वानुमान के लिए उन्नत AI एल्गोरिदम",
  whyItem2: "कंप्यूटर विज़न के साथ रीयल-टाइम फसल स्वास्थ्य निगरानी",
  whyItem3: "व्यापक सरकारी योजनाओं का डेटाबेस",
  whyItem4: "सीधा बाज़ार — कोई बिचौलिया नहीं",
  whyItem5: "सभी तकनीकी स्तरों के किसानों के लिए डिज़ाइन",
  getStartedNow: "अभी शुरू करें",
  cropAnalysisDashboard: "फसल विश्लेषण डैशबोर्ड",
  realTimeMonitoring: "रीयल-टाइम निगरानी",
  health: "स्वास्थ्य",
  pricePerKg: "कीमत/किग्रा",
  yield: "उपज",

  // ── CTA ──
  ctaTitle: "अपनी खेती बदलने के लिए तैयार हैं?",
  ctaSubtitle: "उत्पादकता और लाभप्रदता बढ़ाने के लिए हज़ारों किसान पहले से प्रोजेक्ट किसान का उपयोग कर रहे हैं।",
  startFreeToday: "आज मुफ्त शुरू करें",
  viewDashboard: "डैशबोर्ड देखें",

  // ── Stats ──
  farmersOnPlatform: "प्लेटफॉर्म पर किसान",
  cropsMonitored: "निगरानी की गई फसलें",
  pricePredictions: "मूल्य पूर्वानुमान",
  districtsCovered: "शामिल जिले",

  // ── Footer ──
  footerPlatform: "मंच",
  footerResources: "संसाधन",
  footerCompany: "कंपनी",
  footerWeather: "मौसम",
  footerMarketPrices: "बाज़ार कीमतें",
  footerWorkspace: "कार्यक्षेत्र",
  footerAbout: "हमारे बारे में",
  footerPrivacy: "गोपनीयता नीति",
  footerTerms: "सेवा की शर्तें",
  footerContact: "संपर्क",
  footerDescription: "भारतीय किसानों को स्मार्ट निर्णय लेने और लाभप्रदता बढ़ाने में मदद करने वाले AI-संचालित उपकरण।",
  footerCopyright: "प्रोजेक्ट किसान। सर्वाधिकार सुरक्षित।",
  footerTagline: "भारतीय किसानों के लिए AI के साथ निर्मित",

  // ── Government Schemes ──
  schemesTitle: "सरकारी योजनाएं और ऋण",
  schemesSubtitle: "नवीनतम कृषि सहायता कार्यक्रम, सब्सिडी और ऋण प्रस्तावों की खोज करें",
  searchSchemes: "योजनाएं, ऋण या एजेंसियां खोजें...",
  all: "सभी",
  subsidies: "सब्सिडी",
  loans: "ऋण",
  grants: "अनुदान",
  noSchemesFound: "कोई योजना नहीं मिली",
  noSchemesDesc: "आपकी खोज से मेल खाने वाली कोई योजना नहीं मिली। खोज बदलें या बाद में पुनः प्रयास करें।",
  noSubsidiesFound: "कोई सब्सिडी नहीं मिली",
  noLoansFound: "कोई ऋण नहीं मिला",
  noGrantsFound: "कोई अनुदान नहीं मिला",
  needHelpTitle: "आवेदन में मदद चाहिए?",
  needHelpDesc: "हमारे विशेषज्ञ ऊपर सूचीबद्ध किसी भी योजना की आवेदन प्रक्रिया में आपकी मदद कर सकते हैं।",
  getAppAssistance: "आवेदन सहायता प्राप्त करें",
  by: "द्वारा",
  deadline: "अंतिम तिथि",
  details: "विवरण",

  // ── Crop Health Page ──
  cropHealthTitle: "फसल स्वास्थ्य विश्लेषण",
  cropHealthSubtitle: "AI-संचालित स्वास्थ्य मूल्यांकन और सिफारिशें प्राप्त करने के लिए अपनी फसलों की तस्वीरें अपलोड करें",
  howItWorks: "यह कैसे काम करता है",
  howItWorksDesc: "हमारा AI सिस्टम रोगों, पोषक तत्वों की कमी और अन्य स्वास्थ्य समस्याओं का पता लगा सकता है",
  visualAnalysis: "दृश्य विश्लेषण",
  visualAnalysisDesc: "हमारा AI एल्गोरिदम आपकी फसल की तस्वीरों में दृश्य पैटर्न, रंगों और बनावट का विश्लेषण करता है।",
  diseaseDetection: "रोग पहचान",
  diseaseDetectionDesc: "पत्ती जंग, फफूंदी और ब्लाइट जैसे सामान्य फसल रोगों की उच्च सटीकता से पहचान करता है।",
  healthAssessment: "स्वास्थ्य मूल्यांकन",
  healthAssessmentDesc: "एक समग्र स्वास्थ्य स्कोर प्रदान करता है और चिंता के विशिष्ट क्षेत्रों की पहचान करता है।",
  personalizedRec: "व्यक्तिगत सिफारिशें",
  personalizedRecDesc: "विश्लेषण के आधार पर उपचार, उर्वरक और देखभाल के लिए अनुकूलित सुझाव प्रदान करता है।",
  forBestResults: "सर्वोत्तम परिणामों के लिए",
  tipClearPhotos: "स्पष्ट, अच्छी रोशनी वाली तस्वीरें लें",
  tipAvoidShadows: "छाया और धुंधलापन से बचें",
  tipIncludeParts: "स्वस्थ और अस्वस्थ भागों को शामिल करें",
  tipAngles: "कई कोणों से फोटो दें",
  analysisResults: "विश्लेषण परिणाम",
  confidence: "विश्वसनीयता",
  healthScoreLabel: "स्वास्थ्य स्कोर",
  detectedIssue: "पहचानी गई समस्या",
  recommendations: "सिफारिशें",
  excellent: "उत्कृष्ट",
  good: "अच्छा",
  fair: "ठीक",
  poor: "खराब",
  critical: "गंभीर",
  seasonalCrops: "भारत में मौसमी फसलें",
  seasonalCropsDesc: "वर्तमान मौसम के लिए अनुशंसित फसलें, सामान्य रोग और उपचार विकल्प",
  commonDiseases: "सामान्य रोग",
  symptoms: "लक्षण",
  remedies: "उपचार",
  recommendedFertilizers: "अनुशंसित उर्वरक",
  dataUpdated: "भारत में बढ़ते मौसम के लिए डेटा अपडेटेड",
  consultExperts: "हमेशा स्थानीय कृषि विशेषज्ञों से परामर्श करें",
  checkCropHealthBtn: "फसल स्वास्थ्य जांचें",
  uploadedImage: "अपलोड की गई तस्वीर",
  analyzing: "विश्लेषण हो रहा है...",
  analyzeCropHealth: "फसल स्वास्थ्य का विश्लेषण करें",
  analyzingImage: "तस्वीर का विश्लेषण हो रहा है...",
  analyzingImageDesc: "कृपया प्रतीक्षा करें, हम आपकी फसल के स्वास्थ्य का आकलन कर रहे हैं।",
  analysisComplete: "विश्लेषण पूर्ण",
  analysisCompleteDesc: "हमने आपकी फसल का स्वास्थ्य मूल्यांकन पूरा कर लिया है।",

  // ── Price Estimation ──
  priceEstTitle: "फसल मूल्य अनुमान",
  priceEstSubtitle: "विभिन्न कारकों के आधार पर अपनी फसलों के बाजार मूल्य का अनुमान लगाने के लिए हमारे AI-संचालित उपकरण का उपयोग करें",
  marketAnalysis: "बाज़ार विश्लेषण",
  marketAnalysisDesc: "हमारा AI आधारभूत मूल्य रुझान स्थापित करने के लिए वर्तमान और ऐतिहासिक बाजार डेटा का विश्लेषण करता है।",
  resourceEvaluation: "संसाधन मूल्यांकन",
  resourceEvalDesc: "हम अनुमान को परिष्कृत करने के लिए आपकी भूमि का आकार, पानी की उपलब्धता और मिट्टी के प्रकार को ध्यान में रखते हैं।",
  yieldPrediction: "उपज पूर्वानुमान",
  yieldPredictionDesc: "सिस्टम प्रदान की गई जानकारी के आधार पर आपकी संभावित उपज गुणवत्ता की भविष्यवाणी करता है।",
  priceRangeGen: "मूल्य सीमा निर्माण",
  priceRangeDesc: "आपको न्यूनतम, औसत और अधिकतम अनुमानों के साथ एक व्यापक मूल्य सीमा प्राप्त होती है।",
  didYouKnow: "क्या आप जानते हैं?",
  didYouKnowText: "मूल्य अनुमान उपकरणों का उपयोग करने वाले किसान अपने बाजार प्रवेश का सही समय चुनकर अपने लाभ मार्जिन को 15% तक बढ़ा सकते हैं।",
  cropYieldEstimation: "फसल उपज अनुमान",
  estimate: "अनुमान",
  estimationResult: "अनुमान परिणाम",
  estimatedYield: "अनुमानित उपज:",
  waterRequired: "आवश्यक पानी:",
  diseases: "रोग:",
  fertilizerRec: "उर्वरक सिफारिश:",
  remark: "टिप्पणी:",
  estimatedSales: "अनुमानित बिक्री:",
  estimatedCost: "अनुमानित लागत:",
  fetchError: "अनुमान प्राप्त करने में विफल। कृपया पुनः प्रयास करें।",
  serverError: "सर्वर से कनेक्ट करने में त्रुटि।",

  // ── Direct Market ──
  directMarketTitle: "सीधा बाज़ार पहुंच",
  directMarketSubtitle: "बिचौलियों के बिना अपनी उपज बेचने या पट्टे पर देने के लिए सीधे उपभोक्ताओं और उद्योगों से जुड़ें",
  searchMarket: "उत्पाद, स्थान, या विक्रेता द्वारा खोजें...",
  allListings: "सभी लिस्टिंग",
  forSale: "बिक्री के लिए",
  forLease: "पट्टे के लिए",
  listYourProduct: "अपना उत्पाद सूचीबद्ध करें",
  listNewProduct: "नया उत्पाद सूचीबद्ध करें",
  listNewProductDesc: "बाज़ार में सूचीबद्ध करने के लिए अपने उत्पाद का विवरण दर्ज करें।",
  productTitle: "उत्पाद शीर्षक",
  enterProductName: "उत्पाद का नाम दर्ज करें",
  price: "कीमत",
  priceInRupees: "₹00/इकाई",
  quantityAvailable: "उपलब्ध मात्रा",
  quantityPlaceholder: "उदा., 500 किग्रा उपलब्ध",
  location: "स्थान",
  cityState: "शहर, राज्य",
  sellerName: "विक्रेता का नाम",
  sellerNamePlaceholder: "आपका नाम या व्यवसाय का नाम",
  category: "श्रेणी",
  categoryPlaceholder: "उदा., सब्जियां, अनाज",
  marketType: "बाज़ार प्रकार",
  selectMarketType: "बाज़ार प्रकार चुनें",
  consumerMarket: "उपभोक्ता बाज़ार",
  industrySupply: "उद्योग आपूर्ति",
  equipmentRental: "उपकरण किराया",
  listingType: "लिस्टिंग प्रकार",
  imageUrl: "चित्र URL (वैकल्पिक)",
  enterImageUrl: "चित्र URL दर्ज करें",
  cancel: "रद्द करें",
  listProduct: "उत्पाद सूचीबद्ध करें",
  contactRequestSent: "संपर्क अनुरोध भेजा गया",
  contactRequestDesc: "विक्रेता से संपर्क करने का आपका अनुरोध भेज दिया गया है।",
  missingInfo: "जानकारी अधूरी",
  fillRequired: "कृपया सभी आवश्यक फ़ील्ड भरें।",
  productListed: "उत्पाद सफलतापूर्वक सूचीबद्ध",
  productListedDesc: "आपका उत्पाद बाज़ार में जोड़ दिया गया है।",
  contactSeller: "विक्रेता से संपर्क करें",
  quantity: "मात्रा:",
  seller: "विक्रेता:",
  listingTypeLabel: "लिस्टिंग प्रकार:",
  noProductsFound: "कोई उत्पाद नहीं मिला",
  noProductsHint: "अपनी खोज या फ़िल्टर बदलें",
  beFirstToList: "इस श्रेणी में पहला उत्पाद सूचीबद्ध करें",
  needTransport: "अपने माल के लिए परिवहन चाहिए?",
  needTransportDesc: "अपनी उपज का परिवहन करने के लिए स्थानीय लॉजिस्टिक्स प्रदाताओं से जुड़ें।",
  findTransport: "परिवहन खोजें",

  // ── Prices ──
  cropPrices: "फसल कीमतें",
  cropPricesDesc: "विभिन्न राज्यों में फसलों और वस्तुओं की नवीनतम कीमतें प्राप्त करें। कीमतें दैनिक अपडेट होती हैं।",
  searchCrops: "फसलें खोजें (उदा., गेहूं, चावल, कपास...)",
  allStates: "सभी राज्य",
  showing: "दिखा रहे हैं",
  prices: "कीमत(ें)",
  for: "के लिए",
  in: "में",
  noCropsFound: "आपकी खोज से मेल खाने वाली कोई फसल नहीं मिली।",
  noCropsHint: "अपने खोज शब्द बदलें या कोई भिन्न राज्य चुनें।",
  marketInfo: "बाज़ार जानकारी",
  priceUpdates: "कीमत अपडेट:",
  dailyAt: "प्रतिदिन सुबह 6:00 बजे IST",
  currency: "मुद्रा:",
  inrFull: "भारतीय रुपये (₹)",
  unit: "इकाई:",
  perQuintal: "प्रति क्विंटल (100 किग्रा)",
  pricesDisclaimer: "* कीमतें सांकेतिक हैं और गुणवत्ता, बाजार स्थितियों और स्थानीय कारकों के आधार पर भिन्न हो सकती हैं।",
  per: "प्रति",

  // ── Land Selling ──
  landMarketplace: "कृषि भूमि बाज़ार",
  mapView: "मानचित्र दृश्य",
  addListing: "लिस्टिंग जोड़ें",
  viewListings: "लिस्टिंग देखें",
  maxPrice: "अधिकतम कीमत",
  minArea: "न्यूनतम क्षेत्र (एकड़)",
  title: "शीर्षक",
  area: "क्षेत्र",
  createdAt: "निर्माण तिथि",
  contact: "संपर्क",
  listingsLoaded: "लिस्टिंग लोड हुई",
  listingsLoadedDesc: "डेटाबेस से भूमि लिस्टिंग।",
  error: "त्रुटि",
  failedLoadListings: "लिस्टिंग लोड करने में विफल। कृपया बाद में पुनः प्रयास करें।",
  invalidListing: "अमान्य लिस्टिंग",
  fillAllRequired: "कृपया सभी आवश्यक फ़ील्ड वैध मानों से भरें।",
  listingAdded: "लिस्टिंग जोड़ी गई",
  listingAddedDesc: "आपकी भूमि लिस्टिंग सफलतापूर्वक जोड़ दी गई है।",
  addNewLandListing: "नई भूमि लिस्टिंग जोड़ें",
  addNewLandDesc: "बिक्री के लिए अपनी कृषि भूमि सूचीबद्ध करने के लिए नीचे विवरण भरें",
  listingTitle: "लिस्टिंग शीर्षक",
  listingTitlePlaceholder: "उदा., पुणे के पास उपजाऊ कृषि भूमि",
  description: "विवरण",
  landDescPlaceholder: "अपनी भूमि, मिट्टी की गुणवत्ता, निकटवर्ती जल स्रोतों आदि का वर्णन करें।",
  priceRupees: "कीमत (₹)",
  enterPrice: "कीमत रुपये में दर्ज करें",
  areaAcres: "क्षेत्रफल (एकड़)",
  landAreaAcres: "एकड़ में भूमि क्षेत्रफल",
  contactNumber: "संपर्क नंबर",
  enterContact: "अपना संपर्क नंबर दर्ज करें",
  clickMapInstruction: "स्थान सेट करने के लिए मानचित्र पर क्लिक करें, या मैन्युअल रूप से निर्देशांक दर्ज करें:",
  latitude: "अक्षांश",
  longitude: "देशांतर",
  viewOnGoogleMaps: "Google Maps पर देखें",
  reset: "रीसेट",
  saving: "सहेजा जा रहा है...",
  validationError: "सत्यापन त्रुटि",
  titleRequired: "शीर्षक आवश्यक है",
  descriptionRequired: "विवरण आवश्यक है",
  priceGtZero: "कीमत शून्य से अधिक होनी चाहिए",
  areaGtZero: "क्षेत्रफल शून्य से अधिक होना चाहिए",
  contactRequired: "संपर्क नंबर आवश्यक है",
  success: "सफलता",
  landListingAdded: "भूमि लिस्टिंग सफलतापूर्वक जोड़ी गई!",
  failedAddListing: "लिस्टिंग जोड़ने में विफल। कृपया पुनः प्रयास करें।",
  landListingsMap: "भूमि लिस्टिंग मानचित्र",
  landListingsMapDesc: "बिक्री के लिए उपलब्ध कृषि भूमि ब्राउज़ करें। विवरण देखने के लिए मार्करों पर क्लिक करें।",
  hideFilters: "फ़िल्टर छिपाएं",
  showFilters: "फ़िल्टर दिखाएं",
  searchByTitle: "शीर्षक से खोजें",
  searchListings: "लिस्टिंग खोजें...",
  priceRange: "कीमत सीमा:",
  areaRange: "क्षेत्र सीमा:",
  acres: "एकड़",
  resetFilters: "फ़िल्टर रीसेट करें",
  of: "का",
  listingsShown: "लिस्टिंग दिखाई गई",
  loadingMap: "मानचित्र और लिस्टिंग लोड हो रहे हैं...",
  noListingsAvailable: "कोई लिस्टिंग उपलब्ध नहीं। पहले कुछ लिस्टिंग जोड़ें।",
  listingsAvailable: "लिस्टिंग उपलब्ध",
  recentListings: "हालिया लिस्टिंग:",

  // ── Farmer Pages ──
  farmerPortal: "किसान पोर्टल",
  registerNewAccount: "नया खाता पंजीकृत करें",
  name: "नाम",
  landArea: "भूमि क्षेत्र",
  phoneNumber: "फोन नंबर",
  email: "ईमेल",
  password: "पासवर्ड",
  selectedCrop: "चयनित फसल",
  register: "पंजीकरण",
  registering: "पंजीकरण हो रहा है...",
  alreadyRegistered: "पहले से पंजीकृत?",
  enterPhoneNumber: "फोन नंबर दर्ज करें",
  enterPassword: "पासवर्ड दर्ज करें",
  viewDetails: "विवरण देखें",
  viewMyDetails: "मेरा विवरण देखें",
  errorRegistering: "किसान पंजीकरण में त्रुटि",
  loadingFarmerDetails: "किसान विवरण लोड हो रहे हैं...",
  farmerNotFound: "किसान नहीं मिला",
  farmerDetails: "किसान विवरण",
  nameLabel: "नाम:",
  areaLabel: "क्षेत्र:",
  landAreaLabel: "भूमि क्षेत्र:",
  phoneLabel: "फोन:",
  emailLabel: "ईमेल:",
  dateOfStarting: "शुरू करने की तिथि:",
  selectedCropLabel: "चयनित फसल:",
  notSelected: "चयनित नहीं",
  enterNewCrop: "नई फसल दर्ज करें",
  updating: "अपडेट हो रहा है...",
  updateCrop: "फसल अपडेट करें",
  loadingCropInfo: "फसल जानकारी लोड हो रही है...",
  cropSchedule: "फसल अनुसूची:",
  dailyTasks: "दैनिक कार्य",
  waterSchedule: "पानी अनुसूची",
  growthStages: "विकास चरण",
  fertilizerSchedule: "उर्वरक अनुसूची",
  day: "दिन",
  date: "तिथि",
  activity: "गतिविधि",
  totalCropDuration: "कुल फसल अवधि:",
  days: "दिन",
  sending: "भेजा जा रहा है...",
  sendEmail: "ईमेल भेजें",
  emailSentSuccess: "ईमेल सफलतापूर्वक भेजी!",
  failedSendEmail: "ईमेल भेजने में विफल",
  registrationDate: "पंजीकरण तिथि:",
  cropLabel: "फसल:",
  notApplicable: "लागू नहीं",

  // ── Weather Page ──
  weatherRainfallTitle: "मौसम और वर्षा विश्लेषण",
  weatherRainfallDesc: "अपनी कृषि गतिविधियों की प्रभावी योजना बनाने के लिए वर्षा पैटर्न की निगरानी करें।",
  rainfallDataFor: "वर्षा डेटा",
  next30Days: "(अगले 30 दिन)",
  selectState: "राज्य चुनें",
  rainfallMm: "वर्षा (मिमी)",
  rainfallLabel: "वर्षा:",
  conditionLabel: "स्थिति:",
  weatherImpact: "फसलों पर मौसम का प्रभाव",
  weatherImpactDesc: "वर्षा पैटर्न को समझने से सिंचाई की योजना, उपयुक्त फसल किस्मों के चयन और रोपण कार्यक्रम निर्धारित करने में मदद मिलती है।",
  rainfallRequirements: "वर्षा आवश्यकताएं:",
  seasonalForecasts: "मौसमी पूर्वानुमान",
  seasonalForecastsDesc: "मौसमी पूर्वानुमान कृषि योजना के लिए मूल्यवान अंतर्दृष्टि प्रदान करते हैं।",
  monsoonSeason: "मानसून मौसम (जून-सितंबर)",
  monsoonDesc: "अधिकांश क्षेत्रों में सामान्य से अधिक रहने की उम्मीद है।",
  winterSeason: "शीत ऋतु (अक्टूबर-फरवरी)",
  winterDesc: "उत्तरी और मध्य क्षेत्रों में मध्यम वर्षा की भविष्यवाणी।",

  // ── Token Pages ──
  tokenRegistration: "टोकन पंजीकरण",
  enterName: "नाम दर्ज करें",
  enterContactNumber: "संपर्क नंबर दर्ज करें",
  landAreaInAcres: "भूमि क्षेत्र (एकड़ में)",
  enterEmail: "ईमेल दर्ज करें",
  cropOptional: "फसल (वैकल्पिक)",
  submit: "जमा करें",
  tokenAdded: "टोकन सफलतापूर्वक जोड़ा गया!",
  tokenError: "टोकन जोड़ने में त्रुटि। कृपया पुनः प्रयास करें।",
  checkStatus: "स्थिति जांचें",
  status: "स्थिति:",
  allottedDate: "आवंटित तिथि:",
  noRecordFound: "इस फोन नंबर के लिए कोई रिकॉर्ड नहीं मिला।",
  tokenAllotment: "टोकन आवंटन (केवल एडमिन)",
  adminUsername: "एडमिन यूज़रनेम",
  adminPassword: "एडमिन पासवर्ड",
  farmersPhone: "किसान का फोन नंबर",
  updateStatus: "स्थिति अपडेट करें",
  accessDenied: "पहुंच अस्वीकृत: अमान्य एडमिन क्रेडेंशियल।",
  statusUpdated: "स्थिति और आवंटित तिथि सफलतापूर्वक अपडेट!",
  tokenUpdateError: "टोकन अपडेट करने में त्रुटि। कृपया पुनः प्रयास करें।",

  // ── Seller Management ──
  sellerManagement: "विक्रेता प्रबंधन",
  addNewSeller: "नया विक्रेता जोड़ें",
  itemName: "वस्तु का नाम",
  contactOptional: "संपर्क (वैकल्पिक)",
  sellerAdded: "विक्रेता सफलतापूर्वक जोड़ा गया!",

  // ── Update Crop ──
  updateYourCrop: "अपनी फसल अपडेट करें",
  updateCropPaymentDesc: "अपनी फसल का विवरण अपडेट करने के लिए कृपया ₹100 का सुरक्षित भुगतान करें।",
  payAmount: "₹100 भुगतान करें",
  afterPaymentNote: "भुगतान के बाद आपकी फसल स्वचालित रूप से अपडेट हो जाएगी।",
  paymentSuccessful: "भुगतान सफल! भुगतान आईडी:",
  razorpayFailed: "Razorpay SDK लोड करने में विफल। कृपया पुनः प्रयास करें।",

  // ── Workplace ──
  showData: "डेटा दिखाएं",
  apply: "आवेदन करें",
  welcome: "स्वागत है",
  selectOption: "कृपया ऊपर नेवबार से एक विकल्प चुनें।",

  // ── Work Listings ──
  createWorkListing: "कार्य सूची बनाएं",
  workListingCreated: "कार्य सूची सफलतापूर्वक बनाई गई!",
  failedCreateListing: "कार्य सूची बनाने में विफल",
  errorConnecting: "सर्वर से कनेक्ट करने में त्रुटि। कृपया पुनः प्रयास करें।",
  jobTitle: "कार्य शीर्षक",
  jobTitlePlaceholder: "एक स्पष्ट कार्य शीर्षक दर्ज करें",
  descriptionLabel: "विवरण",
  jobDescPlaceholder: "कार्य का विस्तार से वर्णन करें",
  payment: "भुगतान",
  paymentPlaceholder: "भुगतान राशि या सीमा",
  locationLabel: "स्थान",
  locationPlaceholder: "अल्पविराम से अलग करके स्थान दर्ज करें",
  duration: "अवधि",
  durationPlaceholder: "कार्य की अपेक्षित अवधि",
  categoryLabel: "श्रेणी",
  jobCategoryPlaceholder: "कार्य श्रेणी",
  requirements: "आवश्यकताएं",
  requirementsPlaceholder: "आवश्यक कौशल और योग्यताएं",
  contactInfo: "संपर्क जानकारी",
  contactInfoPlaceholder: "आवेदक आपसे कैसे संपर्क करें",
  submitting: "जमा हो रहा है...",
  createListing: "सूची बनाएं",
  workListings: "कार्य सूचियां",
  failedLoadData: "डेटा लोड करने में विफल। कृपया बाद में पुनः प्रयास करें।",
  loadingListings: "सूचियां लोड हो रही हैं...",
  noWorkListings: "इस समय कोई कार्य सूची उपलब्ध नहीं",
  requirementsLabel: "आवश्यकताएं:",
  applyNow: "अभी आवेदन करें",
  clear: "साफ़ करें",
};

const bn_t: Record<string, string> = {
  sarthiTitle: "সারথী AI সহকারী",
  askPlaceholder: "সারথীকে কিছু জিজ্ঞাসা করুন...",
  welcomeTitle: "সারথীতে স্বাগতম!",
  welcomeSubtitle: "আজ আমি আপনাকে কীভাবে সাহায্য করতে পারি?",
  selectLanguage: "ভাষা নির্বাচন করুন",
  currentLabel: "বর্তমান",
  clickMicToStart: "শুরু করতে মাইকে ক্লিক করুন",
  listening: "শুনছি...",
  sendToChat: "চ্যাটে পাঠান",
  errorResponse: "দুঃখিত, উত্তর পাওয়া যায়নি। আবার চেষ্টা করুন।",
  connectionError: "সার্ভারে সংযোগ করা যাচ্ছে না।",
  typing: "সারথী টাইপ করছে...",
  navHome: "হোম",
  navPriceEstimation: "মূল্য অনুমান",
  navCropHealth: "ফসলের স্বাস্থ্য",
  navSchemes: "প্রকল্প",
  navMarket: "বাজার",
  navLand: "জমি",
  navPrices: "দাম",
  navWeather: "আবহাওয়া",
  navToken: "টোকেন",
  projectKisan: "প্রকল্প",
  projectKisanHighlight: "কিষাণ",
  logIn: "লগ ইন",
  dashboard: "ড্যাশবোর্ড",
  heroBadge: "AI-চালিত কৃষি প্ল্যাটফর্ম",
  heroTitle: "স্মার্ট চাষাবাদ,",
  heroTitleHighlight: "ভালো রিটার্ন",
  heroSubtitle: "ফসলের দাম অনুমান, উদ্ভিদ স্বাস্থ্য পর্যবেক্ষণ, সরকারি প্রকল্প আবিষ্কার এবং সরাসরি ক্রেতাদের সাথে সংযোগ করতে AI ব্যবহার করুন।",
  getStartedFree: "বিনামূল্যে শুরু করুন",
  checkCropHealth: "ফসলের স্বাস্থ্য পরীক্ষা করুন",
  trustedBy: "বিশ্বস্ত",
  trustedCount: "১,০০০+",
  farmersAcrossIndia: "সারা ভারতের কৃষক",
  activeCrops: "সক্রিয় ফসল",
  healthScore: "স্বাস্থ্য স্কোর",
  priceAlerts: "দামের সতর্কতা",
  estRevenue: "আনু. আয়",
  priceTrends: "দামের প্রবণতা",
  last7Days: "গত ৭ দিন",
  features: "বৈশিষ্ট্য",
  featuresTitle: "কৃষকদের যা দরকার,",
  featuresTitleHighlight: "এক জায়গায়",
  featuresSubtitle: "কৃষি কাজকে বিপ্লবী করতে এবং লাভ বাড়াতে AI-চালিত সরঞ্জাম।",
  priceEstimation: "মূল্য অনুমান",
  priceEstimationDesc: "জমি, সম্পদ এবং রিয়েল-টাইম বাজার তথ্যের উপর ভিত্তি করে AI-চালিত ফসলের দাম পূর্বাভাস।",
  aiPowered: "AI-চালিত",
  cropHealth: "ফসলের স্বাস্থ্য",
  cropHealthDesc: "তাৎক্ষণিক স্বাস্থ্য মূল্যায়ন, রোগ শনাক্তকরণ এবং চিকিৎসা পরামর্শের জন্য ফসলের ছবি আপলোড করুন।",
  computerVision: "কম্পিউটার ভিশন",
  govSchemes: "সরকারি প্রকল্প",
  govSchemesDesc: "সর্বশেষ কৃষি ভর্তুকি, ঋণ এবং প্রকল্পের সময়সীমা সম্পর্কে আপডেট থাকুন।",
  updatedWeekly: "সাপ্তাহিক আপডেট",
  directMarket: "সরাসরি বাজার",
  directMarketDesc: "ক্রেতা ও শিল্পের সাথে সরাসরি সংযোগ করুন — মধ্যস্থতাকারী ছাড়াই পণ্য বিক্রি করুন।",
  marketplace: "মার্কেটপ্লেস",
  landRecords: "জমির রেকর্ড",
  landRecordsDesc: "জমির তালিকা পরিচালনা করুন, কৃষি জমি অন্বেষণ করুন এবং মালিকানার রেকর্ড ট্র্যাক করুন।",
  landManagement: "জমি ব্যবস্থাপনা",
  weatherPrices: "আবহাওয়া ও দাম",
  weatherPricesDesc: "আপনার অঞ্চলের জন্য রিয়েল-টাইম আবহাওয়া পূর্বাভাস এবং দৈনিক মন্ডি মূল্য আপডেট।",
  liveData: "লাইভ তথ্য",
  learnMore: "আরও জানুন",
  welcomeToast: "প্রকল্প কিষাণে স্বাগতম",
  welcomeToastDesc: "ভারতীয় কৃষকদের জন্য বিশেষভাবে ডিজাইন করা AI সরঞ্জাম অন্বেষণ করুন।",
  whyBadge: "কেন প্রকল্প কিষাণ",
  whyTitle: "ভারতীয় কৃষির ভবিষ্যতের জন্য নির্মিত",
  whySubtitle: "আমাদের প্ল্যাটফর্ম অত্যাধুনিক AI-কে গভীর কৃষি জ্ঞানের সাথে একত্রিত করে কৃষকদের ডেটা-চালিত সিদ্ধান্ত নিতে সাহায্য করে।",
  whyItem1: "সঠিক মূল্য পূর্বাভাসের জন্য উন্নত AI অ্যালগরিদম",
  whyItem2: "কম্পিউটার ভিশনের সাথে রিয়েল-টাইম ফসলের স্বাস্থ্য পর্যবেক্ষণ",
  whyItem3: "ব্যাপক সরকারি প্রকল্প ডেটাবেস",
  whyItem4: "সরাসরি মার্কেটপ্লেস — কোনো মধ্যস্থতাকারী নেই",
  whyItem5: "সকল প্রযুক্তি স্তরের কৃষকদের জন্য ডিজাইন করা",
  getStartedNow: "এখনই শুরু করুন",
  cropAnalysisDashboard: "ফসল বিশ্লেষণ ড্যাশবোর্ড",
  realTimeMonitoring: "রিয়েল-টাইম পর্যবেক্ষণ",
  health: "স্বাস্থ্য",
  pricePerKg: "দাম/কেজি",
  yield: "ফলন",
  ctaTitle: "আপনার চাষাবাদ রূপান্তর করতে প্রস্তুত?",
  ctaSubtitle: "উৎপাদনশীলতা ও লাভ বাড়াতে হাজার হাজার কৃষক ইতিমধ্যে প্রকল্প কিষাণ ব্যবহার করছেন।",
  startFreeToday: "আজই বিনামূল্যে শুরু করুন",
  viewDashboard: "ড্যাশবোর্ড দেখুন",
  farmersOnPlatform: "প্ল্যাটফর্মে কৃষক",
  cropsMonitored: "পর্যবেক্ষিত ফসল",
  pricePredictions: "মূল্য পূর্বাভাস",
  districtsCovered: "কভার করা জেলা",
  footerPlatform: "প্ল্যাটফর্ম",
  footerResources: "সম্পদ",
  footerCompany: "কোম্পানি",
  footerWeather: "আবহাওয়া",
  footerMarketPrices: "বাজার দাম",
  footerWorkspace: "কর্মক্ষেত্র",
  footerAbout: "আমাদের সম্পর্কে",
  footerPrivacy: "গোপনীয়তা নীতি",
  footerTerms: "সেবার শর্তাবলী",
  footerContact: "যোগাযোগ",
  footerDescription: "ভারতীয় কৃষকদের স্মার্ট সিদ্ধান্ত নিতে এবং লাভ বাড়াতে সাহায্য করার AI-চালিত সরঞ্জাম।",
  footerCopyright: "প্রকল্প কিষাণ। সর্বস্বত্ব সংরক্ষিত।",
  footerTagline: "ভারতীয় কৃষকদের জন্য AI দিয়ে তৈরি",
  schemesTitle: "সরকারি প্রকল্প ও ঋণ",
  schemesSubtitle: "সর্বশেষ কৃষি সহায়তা কার্যক্রম, ভর্তুকি এবং ঋণ অফার আবিষ্কার করুন",
  searchSchemes: "প্রকল্প, ঋণ বা সংস্থা খুঁজুন...",
  all: "সব",
  subsidies: "ভর্তুকি",
  loans: "ঋণ",
  grants: "অনুদান",
  noSchemesFound: "কোনো প্রকল্প পাওয়া যায়নি",
  noSchemesDesc: "আপনার অনুসন্ধানের সাথে মেলে এমন কোনো প্রকল্প পাওয়া যায়নি। অনুসন্ধান পরিবর্তন করুন।",
  noSubsidiesFound: "কোনো ভর্তুকি পাওয়া যায়নি",
  noLoansFound: "কোনো ঋণ পাওয়া যায়নি",
  noGrantsFound: "কোনো অনুদান পাওয়া যায়নি",
  needHelpTitle: "আবেদনে সহায়তা প্রয়োজন?",
  needHelpDesc: "আমাদের বিশেষজ্ঞরা উপরে তালিকাভুক্ত যেকোনো প্রকল্পের আবেদন প্রক্রিয়ায় আপনাকে গাইড করতে পারেন।",
  getAppAssistance: "আবেদন সহায়তা পান",
  by: "দ্বারা",
  deadline: "শেষ তারিখ",
  details: "বিবরণ",
  cropHealthTitle: "ফসলের স্বাস্থ্য বিশ্লেষণ",
  cropHealthSubtitle: "AI-চালিত স্বাস্থ্য মূল্যায়ন পেতে আপনার ফসলের ছবি আপলোড করুন",
  howItWorks: "এটি কীভাবে কাজ করে",
  howItWorksDesc: "আমাদের AI সিস্টেম রোগ, পুষ্টির ঘাটতি এবং অন্যান্য স্বাস্থ্য সমস্যা শনাক্ত করতে পারে",
  visualAnalysis: "ভিজ্যুয়াল বিশ্লেষণ",
  visualAnalysisDesc: "আমাদের AI অ্যালগরিদম আপনার ফসলের ছবিতে ভিজ্যুয়াল প্যাটার্ন, রং এবং টেক্সচার বিশ্লেষণ করে।",
  diseaseDetection: "রোগ শনাক্তকরণ",
  diseaseDetectionDesc: "পাতার মরিচা, গুঁড়ো ছত্রাক এবং ব্লাইটের মতো সাধারণ ফসলের রোগ উচ্চ নির্ভুলতায় শনাক্ত করে।",
  healthAssessment: "স্বাস্থ্য মূল্যায়ন",
  healthAssessmentDesc: "একটি সামগ্রিক স্বাস্থ্য স্কোর প্রদান করে এবং উদ্বেগের নির্দিষ্ট ক্ষেত্র চিহ্নিত করে।",
  personalizedRec: "ব্যক্তিগত পরামর্শ",
  personalizedRecDesc: "বিশ্লেষণের উপর ভিত্তি করে চিকিৎসা, সার এবং যত্নের জন্য কাস্টমাইজড পরামর্শ দেয়।",
  forBestResults: "সেরা ফলাফলের জন্য",
  tipClearPhotos: "স্পষ্ট, ভালো আলোযুক্ত ছবি তুলুন",
  tipAvoidShadows: "ছায়া ও ঝাপসা এড়িয়ে চলুন",
  tipIncludeParts: "সুস্থ ও অসুস্থ অংশ অন্তর্ভুক্ত করুন",
  tipAngles: "একাধিক কোণ থেকে ছবি দিন",
  analysisResults: "বিশ্লেষণ ফলাফল",
  confidence: "আস্থা",
  healthScoreLabel: "স্বাস্থ্য স্কোর",
  detectedIssue: "শনাক্ত সমস্যা",
  recommendations: "পরামর্শ",
  excellent: "চমৎকার",
  good: "ভালো",
  fair: "মোটামুটি",
  poor: "খারাপ",
  critical: "গুরুতর",
  seasonalCrops: "ভারতে মৌসুমী ফসল",
  seasonalCropsDesc: "বর্তমান মৌসুমের জন্য সুপারিশকৃত ফসল, সাধারণ রোগ এবং চিকিৎসা বিকল্প",
  commonDiseases: "সাধারণ রোগ",
  symptoms: "লক্ষণ",
  remedies: "প্রতিকার",
  recommendedFertilizers: "সুপারিশকৃত সার",
  dataUpdated: "ভারতে চাষের মৌসুমের জন্য তথ্য আপডেট করা হয়েছে",
  consultExperts: "সর্বদা স্থানীয় কৃষি বিশেষজ্ঞদের সাথে পরামর্শ করুন",
  checkCropHealthBtn: "ফসলের স্বাস্থ্য পরীক্ষা করুন",
  uploadedImage: "আপলোড করা ছবি",
  analyzing: "বিশ্লেষণ হচ্ছে...",
  analyzeCropHealth: "ফসলের স্বাস্থ্য বিশ্লেষণ করুন",
  analyzingImage: "ছবি বিশ্লেষণ হচ্ছে...",
  analyzingImageDesc: "অনুগ্রহ করে অপেক্ষা করুন, আমরা আপনার ফসলের স্বাস্থ্য মূল্যায়ন করছি।",
  analysisComplete: "বিশ্লেষণ সম্পন্ন",
  analysisCompleteDesc: "আমরা আপনার ফসলের স্বাস্থ্য মূল্যায়ন সম্পন্ন করেছি।",
  priceEstTitle: "ফসলের মূল্য অনুমান",
  priceEstSubtitle: "বিভিন্ন কারণের উপর ভিত্তি করে আপনার ফসলের বাজার মূল্য অনুমান করতে আমাদের AI-চালিত সরঞ্জাম ব্যবহার করুন",
  marketAnalysis: "বাজার বিশ্লেষণ",
  marketAnalysisDesc: "আমাদের AI বেসলাইন মূল্য প্রবণতা প্রতিষ্ঠার জন্য বর্তমান ও ঐতিহাসিক বাজার তথ্য বিশ্লেষণ করে।",
  resourceEvaluation: "সম্পদ মূল্যায়ন",
  resourceEvalDesc: "আমরা অনুমান পরিমার্জন করতে আপনার জমির আকার, পানির প্রাপ্যতা এবং মাটির ধরন বিবেচনা করি।",
  yieldPrediction: "ফলন পূর্বাভাস",
  yieldPredictionDesc: "সিস্টেম প্রদত্ত তথ্যের উপর ভিত্তি করে আপনার সম্ভাব্য ফলন মান পূর্বাভাস দেয়।",
  priceRangeGen: "মূল্য পরিসীমা তৈরি",
  priceRangeDesc: "আপনি ন্যূনতম, গড় এবং সর্বোচ্চ অনুমান সহ একটি ব্যাপক মূল্য পরিসীমা পান।",
  didYouKnow: "আপনি কি জানেন?",
  didYouKnowText: "মূল্য অনুমান সরঞ্জাম ব্যবহারকারী কৃষকরা কৌশলগতভাবে বাজারে প্রবেশের সময় নির্ধারণ করে তাদের লাভ ১৫% পর্যন্ত বাড়াতে পারেন।",
  cropYieldEstimation: "ফসল ফলন অনুমান",
  estimate: "অনুমান",
  estimationResult: "অনুমান ফলাফল",
  estimatedYield: "আনুমানিক ফলন:",
  waterRequired: "প্রয়োজনীয় পানি:",
  diseases: "রোগ:",
  fertilizerRec: "সার সুপারিশ:",
  remark: "মন্তব্য:",
  estimatedSales: "আনুমানিক বিক্রয়:",
  estimatedCost: "আনুমানিক খরচ:",
  fetchError: "অনুমান আনতে ব্যর্থ। অনুগ্রহ করে আবার চেষ্টা করুন।",
  serverError: "সার্ভারে সংযোগ করতে ত্রুটি।",
  directMarketTitle: "সরাসরি বাজার অ্যাক্সেস",
  directMarketSubtitle: "মধ্যস্থতাকারী ছাড়াই আপনার পণ্য বিক্রি বা লিজ দিতে সরাসরি ভোক্তা ও শিল্পের সাথে সংযোগ করুন",
  searchMarket: "পণ্য, স্থান, বা বিক্রেতা দ্বারা খুঁজুন...",
  allListings: "সব তালিকা",
  forSale: "বিক্রয়ের জন্য",
  forLease: "লিজের জন্য",
  listYourProduct: "আপনার পণ্য তালিকাভুক্ত করুন",
  listNewProduct: "নতুন পণ্য তালিকাভুক্ত করুন",
  listNewProductDesc: "মার্কেটপ্লেসে তালিকাভুক্ত করতে আপনার পণ্যের বিবরণ দিন।",
  productTitle: "পণ্যের শিরোনাম",
  enterProductName: "পণ্যের নাম দিন",
  price: "দাম",
  priceInRupees: "₹০০/একক",
  quantityAvailable: "উপলব্ধ পরিমাণ",
  quantityPlaceholder: "যেমন, ৫০০ কেজি উপলব্ধ",
  location: "স্থান",
  cityState: "শহর, রাজ্য",
  sellerName: "বিক্রেতার নাম",
  sellerNamePlaceholder: "আপনার নাম বা ব্যবসার নাম",
  category: "শ্রেণী",
  categoryPlaceholder: "যেমন, সবজি, শস্য",
  marketType: "বাজারের ধরন",
  selectMarketType: "বাজারের ধরন নির্বাচন করুন",
  consumerMarket: "ভোক্তা বাজার",
  industrySupply: "শিল্প সরবরাহ",
  equipmentRental: "সরঞ্জাম ভাড়া",
  listingType: "তালিকার ধরন",
  imageUrl: "ছবির URL (ঐচ্ছিক)",
  enterImageUrl: "ছবির URL দিন",
  cancel: "বাতিল",
  listProduct: "পণ্য তালিকাভুক্ত করুন",
  contactRequestSent: "যোগাযোগ অনুরোধ পাঠানো হয়েছে",
  contactRequestDesc: "বিক্রেতার সাথে যোগাযোগের আপনার অনুরোধ পাঠানো হয়েছে।",
  missingInfo: "তথ্য অসম্পূর্ণ",
  fillRequired: "অনুগ্রহ করে সমস্ত প্রয়োজনীয় ক্ষেত্র পূরণ করুন।",
  productListed: "পণ্য সফলভাবে তালিকাভুক্ত",
  productListedDesc: "আপনার পণ্য মার্কেটপ্লেসে যোগ করা হয়েছে।",
  contactSeller: "বিক্রেতার সাথে যোগাযোগ",
  quantity: "পরিমাণ:",
  seller: "বিক্রেতা:",
  listingTypeLabel: "তালিকার ধরন:",
  noProductsFound: "কোনো পণ্য পাওয়া যায়নি",
  noProductsHint: "আপনার অনুসন্ধান বা ফিল্টার পরিবর্তন করুন",
  beFirstToList: "এই শ্রেণীতে প্রথম পণ্য তালিকাভুক্ত করুন",
  needTransport: "আপনার পণ্যের জন্য পরিবহন দরকার?",
  needTransportDesc: "আপনার পণ্য পরিবহনের জন্য স্থানীয় লজিস্টিক সরবরাহকারীদের সাথে সংযোগ করুন।",
  findTransport: "পরিবহন খুঁজুন",
  cropPrices: "ফসলের দাম",
  cropPricesDesc: "বিভিন্ন রাজ্যে ফসল ও পণ্যের নতুন দাম পান। দাম প্রতিদিন আপডেট হয়।",
  searchCrops: "ফসল খুঁজুন (যেমন, গম, ধান, তুলো...)",
  allStates: "সব রাজ্য",
  showing: "দেখাচ্ছে",
  prices: "দাম",
  for: "এর জন্য",
  in: "এ",
  noCropsFound: "আপনার অনুসন্ধানের সাথে মেলে এমন কোনো ফসল পাওয়া যায়নি।",
  noCropsHint: "আপনার অনুসন্ধান শব্দ পরিবর্তন করুন বা ভিন্ন রাজ্য নির্বাচন করুন।",
  marketInfo: "বাজার তথ্য",
  priceUpdates: "দাম আপডেট:",
  dailyAt: "প্রতিদিন সকাল ৬:০০ IST",
  currency: "মুদ্রা:",
  inrFull: "ভারতীয় রুপি (₹)",
  unit: "একক:",
  perQuintal: "প্রতি কুইন্টাল (১০০ কেজি)",
  pricesDisclaimer: "* দামগুলি নির্দেশক এবং গুণমান, বাজার পরিস্থিতি ও স্থানীয় কারণের উপর ভিত্তি করে পরিবর্তিত হতে পারে।",
  per: "প্রতি",
  landMarketplace: "কৃষি জমি মার্কেটপ্লেস",
  mapView: "মানচিত্র দৃশ্য",
  addListing: "তালিকা যোগ করুন",
  viewListings: "তালিকা দেখুন",
  maxPrice: "সর্বোচ্চ দাম",
  minArea: "ন্যূনতম এলাকা (একর)",
  title: "শিরোনাম",
  area: "এলাকা",
  createdAt: "তৈরির তারিখ",
  contact: "যোগাযোগ",
  error: "ত্রুটি",
  farmerPortal: "কৃষক পোর্টাল",
  registerNewAccount: "নতুন অ্যাকাউন্ট নিবন্ধন করুন",
  name: "নাম",
  landArea: "জমির এলাকা",
  phoneNumber: "ফোন নম্বর",
  email: "ইমেইল",
  password: "পাসওয়ার্ড",
  selectedCrop: "নির্বাচিত ফসল",
  register: "নিবন্ধন",
  registering: "নিবন্ধন হচ্ছে...",
  alreadyRegistered: "ইতিমধ্যে নিবন্ধিত?",
  enterPhoneNumber: "ফোন নম্বর দিন",
  enterPassword: "পাসওয়ার্ড দিন",
  viewDetails: "বিবরণ দেখুন",
  viewMyDetails: "আমার বিবরণ দেখুন",
  loadingFarmerDetails: "কৃষকের বিবরণ লোড হচ্ছে...",
  farmerNotFound: "কৃষক পাওয়া যায়নি",
  farmerDetails: "কৃষক বিবরণ",
  nameLabel: "নাম:",
  areaLabel: "এলাকা:",
  landAreaLabel: "জমির এলাকা:",
  phoneLabel: "ফোন:",
  emailLabel: "ইমেইল:",
  dateOfStarting: "শুরুর তারিখ:",
  selectedCropLabel: "নির্বাচিত ফসল:",
  notSelected: "নির্বাচিত নয়",
  enterNewCrop: "নতুন ফসল দিন",
  updating: "আপডেট হচ্ছে...",
  updateCrop: "ফসল আপডেট করুন",
  cropSchedule: "ফসলের সময়সূচী:",
  day: "দিন",
  date: "তারিখ",
  activity: "কার্যকলাপ",
  totalCropDuration: "মোট ফসল সময়কাল:",
  days: "দিন",
  sending: "পাঠানো হচ্ছে...",
  sendEmail: "ইমেইল পাঠান",
  tokenRegistration: "টোকেন নিবন্ধন",
  enterName: "নাম দিন",
  enterContactNumber: "যোগাযোগ নম্বর দিন",
  landAreaInAcres: "জমির এলাকা (একরে)",
  enterEmail: "ইমেইল দিন",
  cropOptional: "ফসল (ঐচ্ছিক)",
  submit: "জমা দিন",
  tokenAdded: "টোকেন সফলভাবে যোগ করা হয়েছে!",
  tokenError: "টোকেন যোগ করতে ত্রুটি। অনুগ্রহ করে আবার চেষ্টা করুন।",
  checkStatus: "স্থিতি পরীক্ষা করুন",
  status: "স্থিতি:",
  allottedDate: "বরাদ্দ তারিখ:",
  noRecordFound: "এই ফোন নম্বরের জন্য কোনো রেকর্ড পাওয়া যায়নি।",
  tokenAllotment: "টোকেন বরাদ্দ (শুধু অ্যাডমিন)",
  adminUsername: "অ্যাডমিন ইউজারনেম",
  adminPassword: "অ্যাডমিন পাসওয়ার্ড",
  farmersPhone: "কৃষকের ফোন নম্বর",
  updateStatus: "স্থিতি আপডেট করুন",
  sellerManagement: "বিক্রেতা ব্যবস্থাপনা",
  addNewSeller: "নতুন বিক্রেতা যোগ করুন",
  itemName: "পণ্যের নাম",
  contactOptional: "যোগাযোগ (ঐচ্ছিক)",
  sellerAdded: "বিক্রেতা সফলভাবে যোগ করা হয়েছে!",
  updateYourCrop: "আপনার ফসল আপডেট করুন",
  updateCropPaymentDesc: "আপনার ফসলের বিবরণ আপডেট করতে অনুগ্রহ করে ₹১০০ এর নিরাপদ পেমেন্ট করুন।",
  payAmount: "₹১০০ পে করুন",
  afterPaymentNote: "পেমেন্টের পরে আপনার ফসল স্বয়ংক্রিয়ভাবে আপডেট হবে।",
  showData: "তথ্য দেখুন",
  apply: "আবেদন করুন",
  welcome: "স্বাগতম",
  selectOption: "অনুগ্রহ করে উপরের নেভবার থেকে একটি বিকল্প নির্বাচন করুন।",
  createWorkListing: "কাজের তালিকা তৈরি করুন",
  workListings: "কাজের তালিকা",
  jobTitle: "কাজের শিরোনাম",
  descriptionLabel: "বিবরণ",
  payment: "পেমেন্ট",
  locationLabel: "স্থান",
  duration: "সময়কাল",
  categoryLabel: "শ্রেণী",
  requirements: "প্রয়োজনীয়তা",
  contactInfo: "যোগাযোগ তথ্য",
  submitting: "জমা হচ্ছে...",
  createListing: "তালিকা তৈরি করুন",
  loadingListings: "তালিকা লোড হচ্ছে...",
  noWorkListings: "এই মুহূর্তে কোনো কাজের তালিকা উপলব্ধ নেই",
  requirementsLabel: "প্রয়োজনীয়তা:",
  applyNow: "এখনই আবেদন করুন",
  clear: "মুছুন",
};

const te_t: Record<string, string> = {
  sarthiTitle: "సారథి AI సహాయకుడు",
  askPlaceholder: "సారథిని ఏదైనా అడగండి...",
  welcomeTitle: "సారథికి స్వాగతం!",
  welcomeSubtitle: "ఈ రోజు నేను మీకు ఎలా సహాయం చేయగలను?",
  selectLanguage: "భాష ఎంచుకోండి",
  currentLabel: "ప్రస్తుతం",
  clickMicToStart: "ప్రారంభించడానికి మైక్‌పై క్లిక్ చేయండి",
  listening: "వింటున్నాను...",
  sendToChat: "చాట్‌కు పంపండి",
  errorResponse: "క్షమించండి, ప్రతిస్పందన పొందలేకపోయాను.",
  connectionError: "సర్వర్‌కు కనెక్ట్ అవ్వలేదు.",
  typing: "సారథి టైప్ చేస్తోంది...",
  navHome: "హోమ్",
  navPriceEstimation: "ధర అంచనా",
  navCropHealth: "పంట ఆరోగ్యం",
  navSchemes: "పథకాలు",
  navMarket: "మార్కెట్",
  navLand: "భూమి",
  navPrices: "ధరలు",
  navWeather: "వాతావరణం",
  navToken: "టోకెన్",
  projectKisan: "ప్రాజెక్ట్",
  projectKisanHighlight: "కిసాన్",
  logIn: "లాగిన్",
  dashboard: "డాష్‌బోర్డ్",
  heroBadge: "AI-ఆధారిత వ్యవసాయ వేదిక",
  heroTitle: "స్మార్ట్ వ్యవసాయం,",
  heroTitleHighlight: "మెరుగైన రాబడి",
  heroSubtitle: "పంట ధరలను అంచనా వేయడానికి, మొక్కల ఆరోగ్యాన్ని పర్యవేక్షించడానికి, ప్రభుత్వ పథకాలను కనుగొనడానికి AI ఉపయోగించండి.",
  getStartedFree: "ఉచితంగా ప్రారంభించండి",
  checkCropHealth: "పంట ఆరోగ్యం తనిఖీ",
  trustedBy: "నమ్మకమైన",
  trustedCount: "1,000+",
  farmersAcrossIndia: "భారతదేశం అంతటా రైతులు",
  activeCrops: "సక్రియ పంటలు",
  healthScore: "ఆరోగ్య స్కోరు",
  priceAlerts: "ధర హెచ్చరికలు",
  estRevenue: "అంచనా ఆదాయం",
  priceTrends: "ధర ధోరణులు",
  last7Days: "గత 7 రోజులు",
  features: "ఫీచర్లు",
  featuresTitle: "రైతులకు కావలసినవి,",
  featuresTitleHighlight: "ఒకే చోట",
  featuresSubtitle: "వ్యవసాయ కార్యకలాపాలను విప్లవాత్మకంగా మార్చడానికి AI సాధనాలు.",
  priceEstimation: "ధర అంచనా",
  priceEstimationDesc: "భూమి, వనరులు మరియు రియల్-టైమ్ మార్కెట్ డేటా ఆధారంగా AI-ఆధారిత పంట ధర అంచనాలు.",
  aiPowered: "AI-ఆధారిత",
  cropHealth: "పంట ఆరోగ్యం",
  cropHealthDesc: "తక్షణ ఆరోగ్య అంచనాలు, వ్యాధి గుర్తింపు మరియు చికిత్స సలహా కోసం పంట చిత్రాలను అప్‌లోడ్ చేయండి.",
  computerVision: "కంప్యూటర్ విజన్",
  govSchemes: "ప్రభుత్వ పథకాలు",
  govSchemesDesc: "తాజా వ్యవసాయ సబ్సిడీలు, రుణాలు మరియు పథకాల గడువులతో అప్‌డేట్‌గా ఉండండి.",
  updatedWeekly: "వారపు నవీకరణ",
  directMarket: "ప్రత్యక్ష మార్కెట్",
  directMarketDesc: "కొనుగోలుదారులు మరియు పరిశ్రమలతో నేరుగా కనెక్ట్ అవ్వండి — మధ్యవర్తులు లేకుండా ఉత్పత్తులు విక్రయించండి.",
  marketplace: "మార్కెట్‌ప్లేస్",
  landRecords: "భూమి రికార్డులు",
  landRecordsDesc: "భూమి జాబితాలను నిర్వహించండి, వ్యవసాయ భూమిని అన్వేషించండి మరియు యాజమాన్య రికార్డులను ట్రాక్ చేయండి.",
  landManagement: "భూమి నిర్వహణ",
  weatherPrices: "వాతావరణం & ధరలు",
  weatherPricesDesc: "మీ ప్రాంతానికి రియల్-టైమ్ వాతావరణ అంచనాలు మరియు రోజువారీ మండి ధర నవీకరణలు.",
  liveData: "లైవ్ డేటా",
  learnMore: "మరింత తెలుసుకోండి",
  welcomeToast: "ప్రాజెక్ట్ కిసాన్‌కి స్వాగతం",
  welcomeToastDesc: "భారతీయ రైతుల కోసం ప్రత్యేకంగా రూపొందించిన AI సాధనాలను అన్వేషించండి.",
  whyBadge: "ప్రాజెక్ట్ కిసాన్ ఎందుకు",
  whyTitle: "భారతీయ వ్యవసాయ భవిష్యత్తు కోసం నిర్మించబడింది",
  whySubtitle: "మా వేదిక అత్యాధునిక AI ని లోతైన వ్యవసాయ జ్ఞానంతో కలిపి డేటా-ఆధారిత నిర్ణయాలు తీసుకోవడంలో రైతులకు సహాయపడుతుంది.",
  whyItem1: "ఖచ్చితమైన ధర అంచనాల కోసం అధునాతన AI అల్గారిథమ్‌లు",
  whyItem2: "కంప్యూటర్ విజన్‌తో రియల్-టైమ్ పంట ఆరోగ్య పర్యవేక్షణ",
  whyItem3: "సమగ్ర ప్రభుత్వ పథకాల డేటాబేస్",
  whyItem4: "ప్రత్యక్ష మార్కెట్‌ప్లేస్ — మధ్యవర్తులు లేరు",
  whyItem5: "అన్ని టెక్ స్థాయిల రైతుల కోసం రూపొందించబడింది",
  getStartedNow: "ఇప్పుడే ప్రారంభించండి",
  cropAnalysisDashboard: "పంట విశ్లేషణ డాష్‌బోర్డ్",
  realTimeMonitoring: "రియల్-టైమ్ పర్యవేక్షణ",
  health: "ఆరోగ్యం",
  pricePerKg: "ధర/కిలో",
  yield: "దిగుబడి",
  ctaTitle: "మీ వ్యవసాయాన్ని మార్చడానికి సిద్ధంగా ఉన్నారా?",
  ctaSubtitle: "ఉత్పాదకత మరియు లాభదాయకతను పెంచడానికి వేలాది రైతులు ఇప్పటికే ప్రాజెక్ట్ కిసాన్ ఉపయోగిస్తున్నారు.",
  startFreeToday: "ఈ రోజే ఉచితంగా ప్రారంభించండి",
  viewDashboard: "డాష్‌బోర్డ్ చూడండి",
  farmersOnPlatform: "వేదికపై రైతులు",
  cropsMonitored: "పర్యవేక్షించిన పంటలు",
  pricePredictions: "ధర అంచనాలు",
  districtsCovered: "కవర్ చేయబడిన జిల్లాలు",
  footerPlatform: "వేదిక",
  footerResources: "వనరులు",
  footerCompany: "కంపెనీ",
  footerWeather: "వాతావరణం",
  footerMarketPrices: "మార్కెట్ ధరలు",
  footerWorkspace: "వర్క్‌స్పేస్",
  footerAbout: "మా గురించి",
  footerPrivacy: "గోప్యతా విధానం",
  footerTerms: "సేవా నిబంధనలు",
  footerContact: "సంప్రదించండి",
  footerDescription: "భారతీయ రైతులకు తెలివైన నిర్ణయాలు తీసుకోవడంలో మరియు లాభదాయకతను పెంచడంలో సహాయపడే AI-ఆధారిత సాధనాలు.",
  footerCopyright: "ప్రాజెక్ట్ కిసాన్. అన్ని హక్కులు రిజర్వ్ చేయబడ్డాయి.",
  footerTagline: "భారతీయ రైతుల కోసం AI తో నిర్మించబడింది",
  schemesTitle: "ప్రభుత్వ పథకాలు & రుణాలు",
  schemesSubtitle: "తాజా వ్యవసాయ మద్దతు కార్యక్రమాలు, సబ్సిడీలు మరియు రుణ ఆఫర్లను కనుగొనండి",
  searchSchemes: "పథకాలు, రుణాలు లేదా సంస్థలను వెతకండి...",
  all: "అన్నీ",
  subsidies: "సబ్సిడీలు",
  loans: "రుణాలు",
  grants: "గ్రాంట్లు",
  noSchemesFound: "పథకాలు కనుగొనబడలేదు",
  noSchemesDesc: "మీ శోధనకు సరిపోయే పథకాలు కనుగొనబడలేదు. శోధనను మార్చండి.",
  by: "ద్వారా",
  deadline: "గడువు",
  details: "వివరాలు",
  cropHealthTitle: "పంట ఆరోగ్య విశ్లేషణ",
  cropHealthSubtitle: "AI-ఆధారిత ఆరోగ్య అంచనాలు పొందడానికి మీ పంట చిత్రాలను అప్‌లోడ్ చేయండి",
  howItWorks: "ఇది ఎలా పనిచేస్తుంది",
  howItWorksDesc: "మా AI వ్యవస్థ వ్యాధులు, పోషక లోపాలు మరియు ఇతర ఆరోగ్య సమస్యలను గుర్తించగలదు",
  priceEstTitle: "పంట ధర అంచనా",
  priceEstSubtitle: "వివిధ కారకాల ఆధారంగా మీ పంటల మార్కెట్ ధరను అంచనా వేయడానికి మా AI-ఆధారిత సాధనాన్ని ఉపయోగించండి",
  directMarketTitle: "ప్రత్యక్ష మార్కెట్ యాక్సెస్",
  directMarketSubtitle: "మధ్యవర్తులు లేకుండా మీ ఉత్పత్తులను విక్రయించడానికి నేరుగా వినియోగదారులు & పరిశ్రమలతో కనెక్ట్ అవ్వండి",
  cropPrices: "పంట ధరలు",
  cropPricesDesc: "వివిధ రాష్ట్రాల్లో పంటలు & వస్తువుల తాజా ధరలను పొందండి. ధరలు రోజువారీగా నవీకరించబడతాయి.",
  landMarketplace: "వ్యవసాయ భూమి మార్కెట్‌ప్లేస్",
  farmerPortal: "రైతు పోర్టల్",
  registerNewAccount: "కొత్త ఖాతాను నమోదు చేయండి",
  name: "పేరు",
  landArea: "భూమి విస్తీర్ణం",
  phoneNumber: "ఫోన్ నంబర్",
  email: "ఇమెయిల్",
  password: "పాస్‌వర్డ్",
  selectedCrop: "ఎంచుకున్న పంట",
  register: "నమోదు",
  registering: "నమోదు అవుతోంది...",
  viewMyDetails: "నా వివరాలు చూడండి",
  tokenRegistration: "టోకెన్ నమోదు",
  submit: "సమర్పించు",
  checkStatus: "స్థితి తనిఖీ చేయండి",
  tokenAllotment: "టోకెన్ కేటాయింపు (అడ్మిన్ మాత్రమే)",
  updateStatus: "స్థితి నవీకరించండి",
  sellerManagement: "విక్రేత నిర్వహణ",
  addNewSeller: "కొత్త విక్రేతను జోడించండి",
  updateYourCrop: "మీ పంటను నవీకరించండి",
  updateCropPaymentDesc: "మీ పంట వివరాలను నవీకరించడానికి దయచేసి ₹100 సురక్షిత చెల్లింపు చేయండి.",
  payAmount: "₹100 చెల్లించండి",
  showData: "డేటా చూపించు",
  apply: "దరఖాస్తు చేయండి",
  welcome: "స్వాగతం",
  selectOption: "దయచేసి పై నేవ్‌బార్ నుండి ఒక ఎంపికను ఎంచుకోండి.",
  workListings: "పని జాబితాలు",
  applyNow: "ఇప్పుడే దరఖాస్తు చేయండి",
  clear: "క్లియర్",
};

const ta_t: Record<string, string> = {
  sarthiTitle: "சாரதி AI உதவியாளர்",
  askPlaceholder: "சாரதியிடம் ஏதாவது கேளுங்கள்...",
  welcomeTitle: "சாரதிக்கு வரவேற்கிறோம்!",
  welcomeSubtitle: "இன்று நான் உங்களுக்கு எப்படி உதவ முடியும்?",
  selectLanguage: "மொழியைத் தேர்ந்தெடுங்கள்",
  currentLabel: "தற்போது",
  clickMicToStart: "தொடங்க மைக்கைக் கிளிக் செய்யுங்கள்",
  listening: "கேட்கிறேன்...",
  sendToChat: "அரட்டைக்கு அனுப்பு",
  errorResponse: "மன்னிக்கவும், பதிலைப் பெற முடியவில்லை.",
  connectionError: "சேவையகத்துடன் இணைக்க முடியவில்லை.",
  typing: "சாரதி தட்டச்சு செய்கிறது...",
  navHome: "முகப்பு",
  navPriceEstimation: "விலை மதிப்பீடு",
  navCropHealth: "பயிர் ஆரோக்கியம்",
  navSchemes: "திட்டங்கள்",
  navMarket: "சந்தை",
  navLand: "நிலம்",
  navPrices: "விலைகள்",
  navWeather: "வானிலை",
  navToken: "டோக்கன்",
  projectKisan: "திட்டம்",
  projectKisanHighlight: "கிசான்",
  logIn: "உள்நுழை",
  dashboard: "டாஷ்போர்டு",
  heroBadge: "AI-இயக்கப்படும் வேளாண் தளம்",
  heroTitle: "ஸ்மார்ட் விவசாயம்,",
  heroTitleHighlight: "சிறந்த வருமானம்",
  heroSubtitle: "பயிர் விலைகளை மதிப்பிட, தாவர ஆரோக்கியத்தை கண்காணிக்க, அரசு திட்டங்களைக் கண்டறிய AI பயன்படுத்துங்கள்.",
  getStartedFree: "இலவசமாகத் தொடங்கு",
  checkCropHealth: "பயிர் ஆரோக்கியத்தைச் சோதிக்கவும்",
  trustedBy: "நம்பகமான",
  trustedCount: "1,000+",
  farmersAcrossIndia: "இந்தியா முழுவதும் விவசாயிகள்",
  activeCrops: "சுறுசுறுப்பான பயிர்கள்",
  healthScore: "ஆரோக்கிய மதிப்பெண்",
  priceAlerts: "விலை எச்சரிக்கைகள்",
  estRevenue: "மதிப்பிடப்பட்ட வருவாய்",
  priceTrends: "விலை போக்குகள்",
  last7Days: "கடந்த 7 நாட்கள்",
  features: "அம்சங்கள்",
  featuresTitle: "விவசாயிகளுக்கு தேவையானவை,",
  featuresTitleHighlight: "ஒரே இடத்தில்",
  featuresSubtitle: "விவசாய நடவடிக்கைகளை புரட்சிகரமாக மாற்ற AI கருவிகள்.",
  priceEstimation: "விலை மதிப்பீடு",
  priceEstimationDesc: "நிலம், வளங்கள் மற்றும் நிகழ்நேர சந்தை தரவின் அடிப்படையில் AI-இயக்கப்படும் பயிர் விலை கணிப்புகள்.",
  aiPowered: "AI-இயக்கப்படும்",
  cropHealth: "பயிர் ஆரோக்கியம்",
  cropHealthDesc: "உடனடி ஆரோக்கிய மதிப்பீடுகள், நோய் கண்டறிதல் மற்றும் சிகிச்சை ஆலோசனைக்கு பயிர் படங்களைப் பதிவேற்றுங்கள்.",
  computerVision: "கணினி பார்வை",
  govSchemes: "அரசு திட்டங்கள்",
  govSchemesDesc: "சமீபத்திய வேளாண் மானியங்கள், கடன்கள் மற்றும் திட்ட காலக்கெடுவுடன் புதுப்பிக்கப்பட்டிருங்கள்.",
  updatedWeekly: "வாராந்திர புதுப்பிப்பு",
  directMarket: "நேரடி சந்தை",
  directMarketDesc: "வாங்குபவர்கள் & தொழில்களுடன் நேரடியாக இணையுங்கள் — இடைத்தரகர்கள் இல்லாமல் விற்கவும்.",
  marketplace: "சந்தையிடம்",
  landRecords: "நில பதிவுகள்",
  landRecordsDesc: "நில பட்டியல்களை நிர்வகிக்கவும், வேளாண் நிலத்தை ஆராயவும், உரிமை பதிவுகளை கண்காணிக்கவும்.",
  landManagement: "நில மேலாண்மை",
  weatherPrices: "வானிலை & விலைகள்",
  weatherPricesDesc: "உங்கள் பிராந்தியத்திற்கான நிகழ்நேர வானிலை கணிப்புகள் மற்றும் தினசரி மண்டி விலை புதுப்பிப்புகள்.",
  liveData: "நேரடி தரவு",
  learnMore: "மேலும் அறிக",
  welcomeToast: "திட்டம் கிசானுக்கு வரவேற்கிறோம்",
  welcomeToastDesc: "இந்திய விவசாயிகளுக்காக சிறப்பாக வடிவமைக்கப்பட்ட AI கருவிகளை ஆராயுங்கள்.",
  whyBadge: "திட்டம் கிசான் ஏன்",
  whyTitle: "இந்திய வேளாண்மையின் எதிர்காலத்திற்காக கட்டமைக்கப்பட்டது",
  whySubtitle: "எங்கள் தளம் அதிநவீன AI-ஐ ஆழமான வேளாண் அறிவுடன் இணைத்து விவசாயிகள் தரவு-சார்ந்த முடிவுகளை எடுக்க உதவுகிறது.",
  whyItem1: "துல்லியமான விலை கணிப்புகளுக்கான மேம்பட்ட AI வழிமுறைகள்",
  whyItem2: "கணினி பார்வையுடன் நிகழ்நேர பயிர் ஆரோக்கிய கண்காணிப்பு",
  whyItem3: "விரிவான அரசு திட்ட தரவுத்தளம்",
  whyItem4: "நேரடி சந்தையிடம் — இடைத்தரகர்கள் இல்லை",
  whyItem5: "அனைத்து தொழில்நுட்ப நிலைகளின் விவசாயிகளுக்காக வடிவமைக்கப்பட்டது",
  getStartedNow: "இப்போதே தொடங்குங்கள்",
  cropAnalysisDashboard: "பயிர் பகுப்பாய்வு டாஷ்போர்டு",
  realTimeMonitoring: "நிகழ்நேர கண்காணிப்பு",
  health: "ஆரோக்கியம்",
  pricePerKg: "விலை/கிலோ",
  yield: "விளைச்சல்",
  ctaTitle: "உங்கள் விவசாயத்தை மாற்ற தயாரா?",
  ctaSubtitle: "உற்பத்தித்திறன் மற்றும் லாபத்தை அதிகரிக்க ஆயிரக்கணக்கான விவசாயிகள் ஏற்கனவே திட்டம் கிசான் பயன்படுத்துகின்றனர்.",
  startFreeToday: "இன்றே இலவசமாகத் தொடங்குங்கள்",
  viewDashboard: "டாஷ்போர்டைப் பாருங்கள்",
  farmersOnPlatform: "தளத்தில் விவசாயிகள்",
  cropsMonitored: "கண்காணிக்கப்பட்ட பயிர்கள்",
  pricePredictions: "விலை கணிப்புகள்",
  districtsCovered: "உள்ளடக்கிய மாவட்டங்கள்",
  footerPlatform: "தளம்",
  footerResources: "வளங்கள்",
  footerCompany: "நிறுவனம்",
  footerWeather: "வானிலை",
  footerMarketPrices: "சந்தை விலைகள்",
  footerWorkspace: "பணியிடம்",
  footerAbout: "எங்களைப் பற்றி",
  footerPrivacy: "தனியுரிமைக் கொள்கை",
  footerTerms: "சேவை விதிமுறைகள்",
  footerContact: "தொடர்பு",
  footerDescription: "இந்திய விவசாயிகளுக்கு புத்திசாலித்தனமான முடிவுகளை எடுக்கவும் லாபத்தை அதிகரிக்கவும் உதவும் AI-இயக்கப்படும் கருவிகள்.",
  footerCopyright: "திட்டம் கிசான். அனைத்து உரிமைகளும் பாதுகாக்கப்பட்டுள்ளன.",
  footerTagline: "இந்திய விவசாயிகளுக்காக AI உடன் கட்டமைக்கப்பட்டது",
  schemesTitle: "அரசு திட்டங்கள் & கடன்கள்",
  schemesSubtitle: "சமீபத்திய வேளாண் ஆதரவு திட்டங்கள், மானியங்கள் மற்றும் கடன் சலுகைகளைக் கண்டறியுங்கள்",
  searchSchemes: "திட்டங்கள், கடன்கள் அல்லது நிறுவனங்களைத் தேடுங்கள்...",
  all: "அனைத்தும்",
  subsidies: "மானியங்கள்",
  loans: "கடன்கள்",
  grants: "மானியங்கள்",
  noSchemesFound: "திட்டங்கள் கிடைக்கவில்லை",
  noSchemesDesc: "உங்கள் தேடலுக்கு பொருந்தும் திட்டங்கள் கிடைக்கவில்லை. தேடலை மாற்றுங்கள்.",
  by: "மூலம்",
  deadline: "காலக்கெடு",
  details: "விவரங்கள்",
  cropHealthTitle: "பயிர் ஆரோக்கிய பகுப்பாய்வு",
  cropHealthSubtitle: "AI-இயக்கப்படும் ஆரோக்கிய மதிப்பீடுகள் பெற உங்கள் பயிர் படங்களைப் பதிவேற்றுங்கள்",
  howItWorks: "இது எப்படி செயல்படுகிறது",
  howItWorksDesc: "எங்கள் AI அமைப்பு நோய்கள், ஊட்டச்சத்து குறைபாடுகள் மற்றும் பிற ஆரோக்கிய பிரச்சனைகளைக் கண்டறிய முடியும்",
  priceEstTitle: "பயிர் விலை மதிப்பீடு",
  priceEstSubtitle: "பல்வேறு காரணிகளின் அடிப்படையில் உங்கள் பயிர்களின் சந்தை விலையை மதிப்பிட எங்கள் AI கருவியைப் பயன்படுத்துங்கள்",
  directMarketTitle: "நேரடி சந்தை அணுகல்",
  directMarketSubtitle: "இடைத்தரகர்கள் இல்லாமல் உங்கள் விளைபொருட்களை விற்க நுகர்வோர் & தொழில்களுடன் நேரடியாக இணையுங்கள்",
  cropPrices: "பயிர் விலைகள்",
  cropPricesDesc: "பல்வேறு மாநிலங்களில் பயிர்கள் & பொருட்களின் சமீபத்திய விலைகளைப் பெறுங்கள். விலைகள் தினமும் புதுப்பிக்கப்படுகின்றன.",
  landMarketplace: "வேளாண் நிலச் சந்தை",
  farmerPortal: "விவசாயி போர்டல்",
  registerNewAccount: "புதிய கணக்கை பதிவு செய்யுங்கள்",
  name: "பெயர்",
  landArea: "நில பரப்பு",
  phoneNumber: "தொலைபேசி எண்",
  email: "மின்னஞ்சல்",
  password: "கடவுச்சொல்",
  selectedCrop: "தேர்ந்தெடுக்கப்பட்ட பயிர்",
  register: "பதிவு",
  registering: "பதிவு செய்யப்படுகிறது...",
  viewMyDetails: "என் விவரங்களைக் காண்க",
  tokenRegistration: "டோக்கன் பதிவு",
  submit: "சமர்ப்பிக்கவும்",
  checkStatus: "நிலையை சரிபார்க்கவும்",
  tokenAllotment: "டோக்கன் ஒதுக்கீடு (நிர்வாகி மட்டும்)",
  updateStatus: "நிலையைப் புதுப்பிக்கவும்",
  sellerManagement: "விற்பனையாளர் மேலாண்மை",
  addNewSeller: "புதிய விற்பனையாளரைச் சேர்க்கவும்",
  updateYourCrop: "உங்கள் பயிரைப் புதுப்பிக்கவும்",
  updateCropPaymentDesc: "உங்கள் பயிர் விவரங்களைப் புதுப்பிக்க ₹100 பாதுகாப்பான பணம் செலுத்துங்கள்.",
  payAmount: "₹100 செலுத்துங்கள்",
  showData: "தரவைக் காட்டு",
  apply: "விண்ணப்பிக்கவும்",
  welcome: "வரவேற்கிறோம்",
  selectOption: "மேலே உள்ள நேவ்பாரிலிருந்து ஒரு விருப்பத்தைத் தேர்ந்தெடுக்கவும்.",
  workListings: "வேலை பட்டியல்கள்",
  applyNow: "இப்போதே விண்ணப்பிக்கவும்",
  clear: "அழி",
};

/* ─── translations ─── */
const translations: Record<LangCode, Record<string, string>> = { en: en_t, hi: hi_t, bn: bn_t, te: te_t, ta: ta_t };
